"""
This type stub file was generated by pyright.
"""

import functools
import logging
import sympy
import torch
from typing import Any, Union
from sympy.logic.boolalg import Boolean as SympyBoolean, BooleanAtom
from .functions import BitwiseFn_bitwise_and, BitwiseFn_bitwise_or, CeilToInt, CleanDiv, FloatPow, FloatTrueDiv, FloorDiv, FloorToInt, Identity, IntTrueDiv, IsNonOverlappingAndDenseIndicator, Max, Min, Mod, ModularIndexing, OpaqueUnaryFn_log2, PowByNatural, PythonMod, RoundDecimal, RoundToInt, ToFloat, TruncToFloat, TruncToInt, Where

"""
This is a simple interpreter for Sympy expressions that dispatches to
classes following the torch._inductor.virtualized calling convention.
For directness, the interpreter takes the handler directly rather than
consulting the TLS.  It does not use most of the methods on the full
handler; only those with corresponding Sympy expressions.  To see an example
of a full handler, see torch.utils._sympy.value_ranges.ValueRangeAnalysis.
"""
log = ...
@functools.lru_cache(None)
def handlers(): # -> dict[Any, str]:
    ...

ASSOCIATIVE_OPS = ...
_nil = ...
def sympy_interp(analysis, env: dict[sympy.Symbol, Any], expr: Union[sympy.Expr, SympyBoolean], *, index_dtype=..., missing_handler=...): # -> Any:
    ...

