"""
This type stub file was generated by pyright.
"""

from typing import Any, List
from llama_index.core.base.embeddings.base import BaseEmbedding

"""Mock embedding model."""
class MockEmbedding(BaseEmbedding):
    """
    Mock embedding.

    Used for token prediction.

    Args:
        embed_dim (int): embedding dimension

    """
    embed_dim: int
    def __init__(self, embed_dim: int, **kwargs: Any) -> None:
        """Init params."""
        ...
    
    @classmethod
    def class_name(cls) -> str:
        ...
    


