"""
This type stub file was generated by pyright.
"""

import torch
import torch._subclasses.functional_tensor
import torch.utils._pytree as pytree
from torch._C import DispatchKey
from torch._functorch.utils import exposed_in
from torch._higher_order_ops.utils import _set_compilation_env, autograd_not_implemented
from torch._ops import HigherOrderOperator
from torch._subclasses.fake_tensor import FakeTensorMode
from torch.fx.experimental.proxy_tensor import ProxyTorchDispatchMode, _temp_remove_metadata_torch_function_mode, _temp_remove_pre_dispatch_torch_function_mode, disable_proxy_modes_tracing, make_fx, track_tensor_tree
from torch.utils._python_dispatch import _get_current_dispatch_mode

@exposed_in("torch")
def strict_mode(callable, operands): # -> Any | None:
    ...

class StrictMode(HigherOrderOperator):
    def __init__(self) -> None:
        ...
    
    def __call__(self, callable, operands): # -> Any | None:
        ...
    


strict_mode_op = ...
@strict_mode_op.py_impl(DispatchKey.CompositeExplicitAutograd)
def strict_mode_op_dense(callable, operands):
    ...

@strict_mode_op.py_impl(ProxyTorchDispatchMode)
def inner(mode, callable, operands): # -> Any:
    ...

def trace_strict_mode(mode, strict_mode_op, callable, operands): # -> Any:
    ...

@strict_mode_op.py_impl(FakeTensorMode)
def strict_mode_fake_tensor_mode(mode, callable, operands):
    ...

@strict_mode_op.py_functionalize_impl
def strict_mode_func(ctx, callable, inputs):
    ...

