"""
This type stub file was generated by pyright.
"""

from llama_index.core.indices.vector_store.retrievers.auto_retriever import VectorIndexAutoRetriever
from llama_index.core.indices.vector_store.retrievers.retriever import VectorIndexRetriever

__all__ = ["VectorIndexRetriever", "VectorIndexAutoRetriever"]
