"""
This type stub file was generated by pyright.
"""

import torch
import torch.fx as fx
from typing import Callable
from torch.multiprocessing.reductions import StorageWeakRef
from torch.utils import _pytree as pytree
from torch.utils._pytree import tree_flatten

aten = ...
def get_aten_target(node: fx.Node) -> Callable:
    ...

rand_ops = ...
def fx_graph_cse(fx_g: torch.fx.graph.Graph): # -> Graph:
    ...

def strip_overloads(gm): # -> None:
    """
    Modifies the target of graph nodes in :attr:`gm` to strip overloads.

    Args:
        gm(fx.GraphModule): The input Fx graph module to be modified
    """
    ...

def get_placeholders(graph):
    ...

def get_outputs(graph): # -> list[Any]:
    ...

