"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import Any

from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.response.schema import RESPONSE_TYPE
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.llms.llm import LLM
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.response_synthesizers import BaseSynthesizer, ResponseMode
from llama_index.core.schema import NodeWithScore, QueryBundle

dispatcher = ...

class RetrieverQueryEngine(BaseQueryEngine):
    """
    Retriever query engine.

    Args:
        retriever (BaseRetriever): A retriever object.
        response_synthesizer (Optional[BaseSynthesizer]): A BaseSynthesizer
            object.
        callback_manager (Optional[CallbackManager]): A callback manager.

    """
    def __init__(
        self,
        retriever: BaseRetriever,
        response_synthesizer: BaseSynthesizer | None = ...,
        node_postprocessors: list[BaseNodePostprocessor] | None = ...,
        callback_manager: CallbackManager | None = ...,
    ) -> None: ...
    @classmethod
    def from_args(
        cls,
        retriever: BaseRetriever,
        llm: LLM | None = ...,
        response_synthesizer: BaseSynthesizer | None = ...,
        node_postprocessors: list[BaseNodePostprocessor] | None = ...,
        callback_manager: CallbackManager | None = ...,
        response_mode: ResponseMode = ...,
        text_qa_template: BasePromptTemplate | None = ...,
        refine_template: BasePromptTemplate | None = ...,
        summary_template: BasePromptTemplate | None = ...,
        simple_template: BasePromptTemplate | None = ...,
        output_cls: type[BaseModel] | None = ...,
        use_async: bool = ...,
        streaming: bool = ...,
        **kwargs: Any,
    ) -> RetrieverQueryEngine:
        """
        Initialize a RetrieverQueryEngine object.".

        Args:
            retriever (BaseRetriever): A retriever object.
            llm (Optional[LLM]): An instance of an LLM.
            response_synthesizer (Optional[BaseSynthesizer]): An instance of a response
                synthesizer.
            node_postprocessors (Optional[List[BaseNodePostprocessor]]): A list of
                node postprocessors.
            callback_manager (Optional[CallbackManager]): A callback manager.
            response_mode (ResponseMode): A ResponseMode object.
            text_qa_template (Optional[BasePromptTemplate]): A BasePromptTemplate
                object.
            refine_template (Optional[BasePromptTemplate]): A BasePromptTemplate object.
            summary_template (Optional[BasePromptTemplate]): A BasePromptTemplate object.
            simple_template (Optional[BasePromptTemplate]): A BasePromptTemplate object.
            output_cls (Optional[Type[BaseModel]]): The pydantic model to pass to the
                response synthesizer.
            use_async (bool): Whether to use async.
            streaming (bool): Whether to use streaming.

        """
        ...

    def retrieve(self, query_bundle: QueryBundle) -> list[NodeWithScore]: ...
    async def aretrieve(self, query_bundle: QueryBundle) -> list[NodeWithScore]: ...
    def with_retriever(self, retriever: BaseRetriever) -> RetrieverQueryEngine: ...
    def synthesize(
        self,
        query_bundle: QueryBundle,
        nodes: list[NodeWithScore],
        additional_source_nodes: Sequence[NodeWithScore] | None = ...,
    ) -> RESPONSE_TYPE: ...
    async def asynthesize(
        self,
        query_bundle: QueryBundle,
        nodes: list[NodeWithScore],
        additional_source_nodes: Sequence[NodeWithScore] | None = ...,
    ) -> RESPONSE_TYPE: ...
    @property
    def retriever(self) -> BaseRetriever:
        """Get the retriever object."""
        ...
