"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

from markdown_it import MarkdownIt

from .._compat import DATACLASS_KWARGS
from ..ruler import StateBase
from ..token import Token
from ..utils import EnvType

if TYPE_CHECKING: ...

@dataclass(**DATACLASS_KWARGS)
class Delimiter:
    marker: int
    length: int
    token: int
    end: int
    open: bool
    close: bool
    level: bool | None = ...

Scanned = ...

class StateInline(StateBase):
    def __init__(self, src: str, md: MarkdownIt, env: EnvType, outTokens: list[Token]) -> None: ...
    def __repr__(self) -> str: ...
    def pushPending(self) -> Token: ...
    def push(self, ttype: str, tag: str, nesting: Literal[-1, 0, 1]) -> Token:
        """Push new token to "stream".
        If pending text exists - flush it as text token
        """
        ...

    def scanDelims(self, start: int, canSplitWord: bool) -> Scanned:
        """
        Scan a sequence of emphasis-like markers, and determine whether
        it can start an emphasis sequence or end an emphasis sequence.

         - start - position to scan from (it should point at a valid marker);
         - canSplitWord - determine if these markers can be found inside a word

        """
        ...
