"""
This type stub file was generated by pyright.
"""

import io
import json
import logging
import os
import tempfile
import zipfile
import torch
import torch._inductor
import torch.utils._pytree as pytree
from pathlib import Path
from typing import Any, IO, Optional, Union
from typing_extensions import Self
from torch._inductor import config
from torch._inductor.cpp_builder import BuildOptionsBase, CppBuilder
from torch.export._tree_utils import reorder_kwargs
from torch.types import FileLike
from .pt2_archive_constants import AOTINDUCTOR_DIR, ARCHIVE_VERSION, CONSTANTS_DIR, CUSTOM_OBJ_FILENAME_PREFIX

log = ...
class PT2ArchiveWriter:
    def __init__(self, archive_path: FileLike) -> None:
        ...
    
    def __enter__(self) -> Self:
        ...
    
    def __exit__(self, *args) -> None:
        ...
    
    def writestr(self, name: str, data: Union[bytes, str]) -> None:
        ...
    
    def write_file(self, name: str, file_path: str) -> None:
        """
        Copy a file into the archive.
        name: The destination file inside the archive.
        file_path: The source file on disk.
        """
        ...
    


class PT2ArchiveReader:
    def __init__(self, archive_path: str) -> None:
        ...
    
    def __enter__(self) -> Self:
        ...
    
    def __exit__(self, *args) -> None:
        ...
    
    def read(self, name: str) -> bytes:
        ...
    
    def extract_to_path(self, member: str, path: str) -> str:
        ...
    
    def extractall(self, path: str) -> None:
        ...
    
    def get_file_names(self) -> list[str]:
        ...
    


def compile_so(aoti_dir: str, aoti_files: list[str], so_path: str) -> str:
    ...

def package_aoti(archive_file: FileLike, aoti_files: Union[list[str], dict[str, list[str]]]) -> FileLike:
    """
    Saves the AOTInductor generated files to the PT2Archive format.

    Args:
        archive_file: The file name to save the package to.
        aoti_files: This can either be a singular path to a directory containing
        the AOTInductor files, or a dictionary mapping the model name to the
        path to its AOTInductor generated files.
    """
    ...

class AOTICompiledModel:
    """
    Callable AOT Inductor loaded model from a .pt2
    """
    def __init__(self, loader: torch._C._aoti.AOTIModelPackageLoader) -> None:
        ...
    
    def __call__(self, *args, **kwargs): # -> PyTree:
        ...
    
    def get_metadata(self) -> dict[str, str]:
        ...
    
    def load_constants(self, constants_map: dict[str, torch.Tensor], *, check_full_update: bool) -> None:
        """
        Given a mapping of constant fqns to tensors, load the constants into the model.
        You can use ``get_constant_fqns`` to get the list of constant fqns that
        are needed in the compiled model.

        Args:
            constants_map: A mapping of constant fqns to tensors.
            check_full_update: Whether to add check to see if all the constants
            are updated and have values.
        """
        ...
    
    def get_constant_fqns(self) -> list[str]:
        ...
    
    def __deepcopy__(self, memo: Optional[dict[Any, Any]]) -> AOTICompiledModel:
        ...
    


def load_package(path: FileLike, model_name: str = ..., run_single_threaded: bool = ...) -> AOTICompiledModel:
    ...

