"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from typing import TYPE_CHECKING

from llama_index.core.base.llms.types import LLMMetadata
from llama_index.core.llms.llm import LLM
from llama_index.core.node_parser.text.token import TokenTextSplitter
from llama_index.core.prompts import BasePromptTemplate
from llama_index.core.schema import BaseComponent
from llama_index.core.tools import BaseTool
from llama_index.core.utilities.token_counting import TokenCounter

"""
General prompt helper that can help deal with LLM context window token limitations.

At its core, it calculates available context size by starting with the context window
size of an LLM and reserve token space for the prompt template, and the output.

It provides utility for "repacking" text chunks (retrieved from index) to maximally
make use of the available context window (and thereby reducing the number of LLM calls
needed), or truncating them so that they fit in a single LLM call.
"""
if TYPE_CHECKING: ...
DEFAULT_PADDING = ...
DEFAULT_CHUNK_OVERLAP_RATIO = ...
logger = ...

class PromptHelper(BaseComponent):
    """
    Prompt helper.

    General prompt helper that can help deal with LLM context window token limitations.

    At its core, it calculates available context size by starting with the context
    window size of an LLM and reserve token space for the prompt template, and the
    output.

    It provides utility for "repacking" text chunks (retrieved from index) to maximally
    make use of the available context window (and thereby reducing the number of LLM
    calls needed), or truncating them so that they fit in a single LLM call.

    Args:
        context_window (int):                   Context window for the LLM.
        num_output (int):                       Number of outputs for the LLM.
        chunk_overlap_ratio (float):            Chunk overlap as a ratio of chunk size
        chunk_size_limit (Optional[int]):         Maximum chunk size to use.
        tokenizer (Optional[Callable[[str], List]]): Tokenizer to use.
        separator (str):                        Separator for text splitter

    """

    context_window: int = ...
    num_output: int = ...
    chunk_overlap_ratio: float = ...
    chunk_size_limit: int | None = ...
    separator: str = ...
    _token_counter: TokenCounter = ...
    def __init__(
        self,
        context_window: int = ...,
        num_output: int = ...,
        chunk_overlap_ratio: float = ...,
        chunk_size_limit: int | None = ...,
        tokenizer: Callable[[str], list] | None = ...,
        separator: str = ...,
    ) -> None:
        """Init params."""
        ...

    @classmethod
    def from_llm_metadata(
        cls,
        llm_metadata: LLMMetadata,
        chunk_overlap_ratio: float = ...,
        chunk_size_limit: int | None = ...,
        tokenizer: Callable[[str], list] | None = ...,
        separator: str = ...,
    ) -> PromptHelper:
        """
        Create from llm predictor.

        This will autofill values like context_window and num_output.

        """
        ...

    @classmethod
    def class_name(cls) -> str: ...
    def get_text_splitter_given_prompt(
        self,
        prompt: BasePromptTemplate,
        num_chunks: int = ...,
        padding: int = ...,
        llm: LLM | None = ...,
        tools: list[BaseTool] | None = ...,
    ) -> TokenTextSplitter:
        """
        Get text splitter configured to maximally pack available context window,
        taking into account of given prompt, and desired number of chunks.
        """
        ...

    def truncate(
        self,
        prompt: BasePromptTemplate,
        text_chunks: Sequence[str],
        padding: int = ...,
        llm: LLM | None = ...,
        tools: list[BaseTool] | None = ...,
    ) -> list[str]:
        """Truncate text chunks to fit available context window."""
        ...

    def repack(
        self,
        prompt: BasePromptTemplate,
        text_chunks: Sequence[str],
        padding: int = ...,
        llm: LLM | None = ...,
        tools: list[BaseTool] | None = ...,
    ) -> list[str]:
        """
        Repack text chunks to fit available context window.

        This will combine text chunks into consolidated chunks
        that more fully "pack" the prompt template given the context_window.

        """
        ...
