"""
This type stub file was generated by pyright.
"""

import torch
import torch.utils.checkpoint
from typing import Callable, List, Optional, Tuple, Union
from torch import nn
from ...activations import ACT2FN
from ...cache_utils import Cache, DynamicCache
from ...modeling_flash_attention_utils import FlashAttentionKwargs
from ...modeling_outputs import BaseModelOutputWithPast
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS
from ...processing_utils import Unpack
from ...utils import logging
from ..mistral.modeling_mistral import MistralAttention, MistralDecoderLayer, MistralForCausalLM, MistralForSequenceClassification, MistralForTokenClassification, MistralModel, MistralPreTrainedModel, MistralRotaryEmbedding, apply_rotary_pos_emb, eager_attention_forward
from .configuration_starcoder2 import Starcoder2Config

"""PyTorch Starcoder2 model."""
logger = ...
class Starcoder2MLP(nn.Module):
    def __init__(self, config: Starcoder2Config) -> None:
        ...
    
    def forward(self, hidden_states: Optional[Tuple[torch.FloatTensor]]) -> torch.FloatTensor:
        ...
    


class Starcoder2Attention(MistralAttention):
    def __init__(self, config: Starcoder2Config, layer_idx: Optional[int] = ...) -> None:
        ...
    
    def forward(self, hidden_states: torch.Tensor, position_embeddings: Tuple[torch.Tensor, torch.Tensor], attention_mask: Optional[torch.Tensor], past_key_value: Optional[Cache] = ..., cache_position: Optional[torch.LongTensor] = ..., **kwargs: Unpack[FlashAttentionKwargs]) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:
        ...
    


class Starcoder2DecoderLayer(MistralDecoderLayer):
    def __init__(self, config: Starcoder2Config, layer_idx: int) -> None:
        ...
    


class Starcoder2RotaryEmbedding(MistralRotaryEmbedding):
    ...


class Starcoder2PreTrainedModel(MistralPreTrainedModel):
    ...


class Starcoder2Model(MistralModel):
    def __init__(self, config: Starcoder2Config) -> None:
        ...
    
    def forward(self, input_ids: Optional[torch.LongTensor] = ..., attention_mask: Optional[torch.Tensor] = ..., position_ids: Optional[torch.LongTensor] = ..., past_key_values: Optional[Union[Cache, List[torch.FloatTensor]]] = ..., inputs_embeds: Optional[torch.FloatTensor] = ..., use_cache: Optional[bool] = ..., output_attentions: Optional[bool] = ..., output_hidden_states: Optional[bool] = ..., cache_position: Optional[torch.LongTensor] = ..., **flash_attn_kwargs: Unpack[FlashAttentionKwargs]) -> BaseModelOutputWithPast:
        ...
    


class Starcoder2ForCausalLM(MistralForCausalLM):
    ...


class Starcoder2ForSequenceClassification(MistralForSequenceClassification):
    ...


class Starcoder2ForTokenClassification(MistralForTokenClassification):
    ...


__all__ = ["Starcoder2ForCausalLM", "Starcoder2Model", "Starcoder2PreTrainedModel", "Starcoder2ForSequenceClassification", "Starcoder2ForTokenClassification"]
