"""
This type stub file was generated by pyright.
"""

from llama_index.core.prompts.base import BasePromptTemplate

def get_empty_prompt_txt(prompt: BasePromptTemplate) -> str:
    """
    Get empty prompt text.

    Substitute empty strings in parts of the prompt that have
    not yet been filled out. Skip variables that have already
    been partially formatted. This is used to compute the initial tokens.

    """
    ...

def get_biggest_prompt(prompts: list[BasePromptTemplate]) -> BasePromptTemplate:
    """
    Get biggest prompt.

    Oftentimes we need to fetch the biggest prompt, in order to
    be the most conservative about chunking text. This
    is a helper utility for that.

    """
    ...
