"""
This type stub file was generated by pyright.
"""

from collections.abc import Generator
from typing import Any

from deprecated import deprecated
from llama_index.core.llms.llm import LLM
from llama_index.core.program.llm_prompt_program import BaseLLMFunctionProgram
from llama_index.core.prompts.base import BasePromptTemplate, PromptTemplate
from llama_index.core.types import Model

_logger = ...

@deprecated("Please use `FunctionCallingProgram` instead.")
class OpenAIPydanticProgram(BaseLLMFunctionProgram[LLM]):
    """
    An OpenAI-based function that returns a pydantic model.

    Note: this interface is not yet stable.
    """
    def __init__(
        self,
        output_cls: type[Model],
        llm: LLM,
        prompt: BasePromptTemplate,
        tool_choice: str | dict[str, Any],
        allow_multiple: bool = ...,
        verbose: bool = ...,
    ) -> None:
        """Init params."""
        ...

    @classmethod
    def from_defaults(
        cls,
        output_cls: type[Model],
        prompt_template_str: str | None = ...,
        prompt: PromptTemplate | None = ...,
        llm: LLM | None = ...,
        verbose: bool = ...,
        allow_multiple: bool = ...,
        tool_choice: str | dict[str, Any] | None = ...,
        **kwargs: Any,
    ) -> OpenAIPydanticProgram: ...
    @property
    def output_cls(self) -> type[Model]: ...
    @property
    def prompt(self) -> BasePromptTemplate: ...
    @prompt.setter
    def prompt(self, prompt: BasePromptTemplate) -> None: ...
    def __call__(
        self, llm_kwargs: dict[str, Any] | None = ..., *args: Any, **kwargs: Any
    ) -> Model | list[Model]: ...
    async def acall(
        self, llm_kwargs: dict[str, Any] | None = ..., *args: Any, **kwargs: Any
    ) -> Model | list[Model]: ...
    def stream_list(
        self, llm_kwargs: dict[str, Any] | None = ..., *args: Any, **kwargs: Any
    ) -> Generator[Model, None, None]:
        """Streams a list of objects."""
        ...

    def stream_partial_objects(
        self, llm_kwargs: dict[str, Any] | None = ..., *args: Any, **kwargs: Any
    ) -> Generator[Model, None, None]:
        """Streams the intermediate partial object."""
        ...
