"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Dict, Generator, List, Optional, Tuple, Type, Union, cast
from llama_index.core.bridge.pydantic import ValidationError
from llama_index.agent.openai.utils import resolve_tool_choice
from llama_index.core.llms.llm import LLM
from llama_index.core.program.llm_prompt_program import BaseLLMFunctionProgram
from llama_index.core.program.utils import create_list_model
from llama_index.core.prompts.base import BasePromptTemplate, PromptTemplate
from llama_index.core.settings import Settings
from llama_index.core.types import Model
from llama_index.llms.openai import OpenAI
from llama_index.llms.openai.utils import OpenAIToolCall, to_openai_tool
from deprecated import deprecated
from llama_index.program.openai.utils import parse_partial_json

_logger = ...
@deprecated("Please use `FunctionCallingProgram` instead.")
class OpenAIPydanticProgram(BaseLLMFunctionProgram[LLM]):
    """
    An OpenAI-based function that returns a pydantic model.

    Note: this interface is not yet stable.
    """
    def __init__(self, output_cls: Type[Model], llm: LLM, prompt: BasePromptTemplate, tool_choice: Union[str, Dict[str, Any]], allow_multiple: bool = ..., verbose: bool = ...) -> None:
        """Init params."""
        ...
    
    @classmethod
    def from_defaults(cls, output_cls: Type[Model], prompt_template_str: Optional[str] = ..., prompt: Optional[PromptTemplate] = ..., llm: Optional[LLM] = ..., verbose: bool = ..., allow_multiple: bool = ..., tool_choice: Optional[Union[str, Dict[str, Any]]] = ..., **kwargs: Any) -> OpenAIPydanticProgram:
        ...
    
    @property
    def output_cls(self) -> Type[Model]:
        ...
    
    @property
    def prompt(self) -> BasePromptTemplate:
        ...
    
    @prompt.setter
    def prompt(self, prompt: BasePromptTemplate) -> None:
        ...
    
    def __call__(self, llm_kwargs: Optional[Dict[str, Any]] = ..., *args: Any, **kwargs: Any) -> Union[Model, List[Model]]:
        ...
    
    async def acall(self, llm_kwargs: Optional[Dict[str, Any]] = ..., *args: Any, **kwargs: Any) -> Union[Model, List[Model]]:
        ...
    
    def stream_list(self, llm_kwargs: Optional[Dict[str, Any]] = ..., *args: Any, **kwargs: Any) -> Generator[Model, None, None]:
        """Streams a list of objects."""
        ...
    
    def stream_partial_objects(self, llm_kwargs: Optional[Dict[str, Any]] = ..., *args: Any, **kwargs: Any) -> Generator[Model, None, None]:
        """Streams the intermediate partial object."""
        ...
    


