"""
This type stub file was generated by pyright.
"""

import asyncio
from inspect import signature
from typing import Any, Awaitable, Callable, Dict, List, Optional, Tuple, Type, Union
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.tools.function_tool import FunctionTool
from llama_index.core.tools.types import ToolMetadata

"""Base tool spec class."""
AsyncCallable = Callable[..., Awaitable[Any]]
SPEC_FUNCTION_TYPE = Union[str, Tuple[str, str]]
class BaseToolSpec:
    """Base tool spec class."""
    spec_functions: List[SPEC_FUNCTION_TYPE]
    def get_fn_schema_from_fn_name(self, fn_name: str, spec_functions: Optional[List[SPEC_FUNCTION_TYPE]] = ...) -> Optional[Type[BaseModel]]:
        """
        NOTE: This function is deprecated and kept only for backwards compatibility.

        Return map from function name.

        Return type is Optional, meaning that the schema can be None.
        In this case, it's up to the downstream tool implementation to infer the schema.

        """
        ...
    
    def get_metadata_from_fn_name(self, fn_name: str, spec_functions: Optional[List[SPEC_FUNCTION_TYPE]] = ...) -> Optional[ToolMetadata]:
        """
        NOTE: This function is deprecated and kept only for backwards compatibility.

        Return map from function name.

        Return type is Optional, meaning that the schema can be None.
        In this case, it's up to the downstream tool implementation to infer the schema.

        """
        ...
    
    def to_tool_list(self, spec_functions: Optional[List[SPEC_FUNCTION_TYPE]] = ..., func_to_metadata_mapping: Optional[Dict[str, ToolMetadata]] = ...) -> List[FunctionTool]:
        """Convert tool spec to list of tools."""
        ...
    


