"""
This type stub file was generated by pyright.
"""

import torch.cuda
from torch._C import _cudnn

def get_cudnn_mode(mode): # -> int:
    ...

class Unserializable:
    def __init__(self, inner) -> None:
        ...
    
    def get(self): # -> Any | None:
        ...
    
    def __getstate__(self): # -> Literal['<unserializable>']:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    


def init_dropout_state(dropout, train, dropout_seed, dropout_state):
    ...

