"""
This type stub file was generated by pyright.
"""

import fsspec
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional, Protocol, Sequence, Union, runtime_checkable
from deprecated import deprecated
from llama_index.core.bridge.pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from llama_index.core.schema import BaseComponent, BaseNode, TextNode

"""Vector store index types."""
DEFAULT_PERSIST_DIR = ...
DEFAULT_PERSIST_FNAME = ...
NodeWithEmbedding = TextNode
@dataclass
class VectorStoreQueryResult:
    """Vector store query result."""
    nodes: Optional[Sequence[BaseNode]] = ...
    similarities: Optional[List[float]] = ...
    ids: Optional[List[str]] = ...


class VectorStoreQueryMode(str, Enum):
    """Vector store query mode."""
    DEFAULT = ...
    SPARSE = ...
    HYBRID = ...
    TEXT_SEARCH = ...
    SEMANTIC_HYBRID = ...
    SVM = ...
    LOGISTIC_REGRESSION = ...
    LINEAR_REGRESSION = ...
    MMR = ...


class FilterOperator(str, Enum):
    """Vector store filter operator."""
    EQ = ...
    GT = ...
    LT = ...
    NE = ...
    GTE = ...
    LTE = ...
    IN = ...
    NIN = ...
    ANY = ...
    ALL = ...
    TEXT_MATCH = ...
    TEXT_MATCH_INSENSITIVE = ...
    CONTAINS = ...
    IS_EMPTY = ...


class FilterCondition(str, Enum):
    """Vector store filter conditions to combine different filters."""
    AND = ...
    OR = ...
    NOT = ...


class MetadataFilter(BaseModel):
    r"""
    Comprehensive metadata filter for vector stores to support more operators.

    Value uses Strict types, as int, float and str are compatible types and were all
    converted to string before.

    See: https://docs.pydantic.dev/latest/usage/types/#strict-types
    """
    key: str
    value: Optional[Union[StrictInt, StrictFloat, StrictStr, List[StrictStr], List[StrictFloat], List[StrictInt],]]
    operator: FilterOperator = ...
    @classmethod
    def from_dict(cls, filter_dict: Dict) -> MetadataFilter:
        """
        Create MetadataFilter from dictionary.

        Args:
            filter_dict: Dict with key, value and operator.

        """
        ...
    


ExactMatchFilter = MetadataFilter
class MetadataFilters(BaseModel):
    """Metadata filters for vector stores."""
    filters: List[Union[MetadataFilter, ExactMatchFilter, MetadataFilters]]
    condition: Optional[FilterCondition] = ...
    @classmethod
    @deprecated("`from_dict()` is deprecated. " "Please use `MetadataFilters(filters=.., condition='and')` directly instead.")
    def from_dict(cls, filter_dict: Dict) -> MetadataFilters:
        """Create MetadataFilters from json."""
        ...
    
    @classmethod
    def from_dicts(cls, filter_dicts: List[Dict], condition: Optional[FilterCondition] = ...) -> MetadataFilters:
        """
        Create MetadataFilters from dicts.

        This takes in a list of individual MetadataFilter objects, along
        with the condition.

        Args:
            filter_dicts: List of dicts, each dict is a MetadataFilter.
            condition: FilterCondition to combine different filters.

        """
        ...
    
    def legacy_filters(self) -> List[ExactMatchFilter]:
        """Convert MetadataFilters to legacy ExactMatchFilters."""
        ...
    


class VectorStoreQuerySpec(BaseModel):
    """
    Schema for a structured request for vector store
    (i.e. to be converted to a VectorStoreQuery).

    Currently only used by VectorIndexAutoRetriever.
    """
    query: str
    filters: List[MetadataFilter]
    top_k: Optional[int] = ...


class MetadataInfo(BaseModel):
    """
    Information about a metadata filter supported by a vector store.

    Currently only used by VectorIndexAutoRetriever.
    """
    name: str
    type: str
    description: str
    ...


class VectorStoreInfo(BaseModel):
    """
    Information about a vector store (content and supported metadata filters).

    Currently only used by VectorIndexAutoRetriever.
    """
    metadata_info: List[MetadataInfo]
    content_info: str
    ...


@dataclass
class VectorStoreQuery:
    """Vector store query."""
    query_embedding: Optional[List[float]] = ...
    similarity_top_k: int = ...
    doc_ids: Optional[List[str]] = ...
    node_ids: Optional[List[str]] = ...
    query_str: Optional[str] = ...
    output_fields: Optional[List[str]] = ...
    embedding_field: Optional[str] = ...
    mode: VectorStoreQueryMode = ...
    alpha: Optional[float] = ...
    filters: Optional[MetadataFilters] = ...
    mmr_threshold: Optional[float] = ...
    sparse_top_k: Optional[int] = ...
    hybrid_top_k: Optional[int] = ...


@runtime_checkable
class VectorStore(Protocol):
    """Abstract vector store protocol."""
    stores_text: bool
    is_embedding_query: bool = ...
    @property
    def client(self) -> Any:
        """Get client."""
        ...
    
    def add(self, nodes: List[BaseNode], **add_kwargs: Any) -> List[str]:
        """Add nodes with embedding to vector store."""
        ...
    
    async def async_add(self, nodes: List[BaseNode], **kwargs: Any) -> List[str]:
        """
        Asynchronously add nodes with embedding to vector store.
        NOTE: this is not implemented for all vector stores. If not implemented,
        it will just call add synchronously.
        """
        ...
    
    def delete(self, ref_doc_id: str, **delete_kwargs: Any) -> None:
        """
        Delete nodes using with ref_doc_id."""
        ...
    
    async def adelete(self, ref_doc_id: str, **delete_kwargs: Any) -> None:
        """
        Delete nodes using with ref_doc_id.
        NOTE: this is not implemented for all vector stores. If not implemented,
        it will just call delete synchronously.
        """
        ...
    
    def query(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
        """Query vector store."""
        ...
    
    async def aquery(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
        """
        Asynchronously query vector store.
        NOTE: this is not implemented for all vector stores. If not implemented,
        it will just call query synchronously.
        """
        ...
    
    def persist(self, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        ...
    


class BasePydanticVectorStore(BaseComponent, ABC):
    """Abstract vector store protocol."""
    model_config = ...
    stores_text: bool
    is_embedding_query: bool = ...
    @property
    @abstractmethod
    def client(self) -> Any:
        """Get client."""
        ...
    
    def get_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ...) -> List[BaseNode]:
        """Get nodes from vector store."""
        ...
    
    async def aget_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ...) -> List[BaseNode]:
        """Asynchronously get nodes from vector store."""
        ...
    
    @abstractmethod
    def add(self, nodes: Sequence[BaseNode], **kwargs: Any) -> List[str]:
        """Add nodes to vector store."""
        ...
    
    async def async_add(self, nodes: Sequence[BaseNode], **kwargs: Any) -> List[str]:
        """
        Asynchronously add nodes to vector store.
        NOTE: this is not implemented for all vector stores. If not implemented,
        it will just call add synchronously.
        """
        ...
    
    @abstractmethod
    def delete(self, ref_doc_id: str, **delete_kwargs: Any) -> None:
        """
        Delete nodes using with ref_doc_id."""
        ...
    
    async def adelete(self, ref_doc_id: str, **delete_kwargs: Any) -> None:
        """
        Delete nodes using with ref_doc_id.
        NOTE: this is not implemented for all vector stores. If not implemented,
        it will just call delete synchronously.
        """
        ...
    
    def delete_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ..., **delete_kwargs: Any) -> None:
        """Delete nodes from vector store."""
        ...
    
    async def adelete_nodes(self, node_ids: Optional[List[str]] = ..., filters: Optional[MetadataFilters] = ..., **delete_kwargs: Any) -> None:
        """Asynchronously delete nodes from vector store."""
        ...
    
    def clear(self) -> None:
        """Clear all nodes from configured vector store."""
        ...
    
    async def aclear(self) -> None:
        """Asynchronously clear all nodes from configured vector store."""
        ...
    
    @abstractmethod
    def query(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
        """Query vector store."""
        ...
    
    async def aquery(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
        """
        Asynchronously query vector store.
        NOTE: this is not implemented for all vector stores. If not implemented,
        it will just call query synchronously.
        """
        ...
    
    def persist(self, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        ...
    


