"""
This type stub file was generated by pyright.
"""

from llama_index.core.schema import BaseNode

def doc_to_json(doc: BaseNode) -> dict: ...
def json_to_doc(doc_dict: dict) -> BaseNode: ...
def legacy_json_to_doc(doc_dict: dict) -> BaseNode:
    """Todo: Deprecated legacy support for old node versions."""
    ...
