"""
This type stub file was generated by pyright.
"""

import math
import torch
from typing import Optional, Union

"""Defines utilities for interacting with scaled_dot_product_attention"""
__all__: list[str] = ...
_SUPPORTED_HEAD_DIMS = ...
