"""
This type stub file was generated by pyright.
"""

from typing import Any

def md_to_df(md_str: str) -> Any:
    """Convert Markdown to dataframe."""
    ...

def html_to_df(html_str: str) -> Any:
    """Convert HTML to dataframe."""
    ...
