"""
This type stub file was generated by pyright.
"""

from typing import Callable, Dict, List, Optional
from llama_index.core.base.llms.types import ChatMessage, ChatResponse, ChatResponseAsyncGen, ChatResponseGen, MessageRole
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import ChatPromptTemplate, PromptTemplate
from llama_index.core.response_synthesizers import CompactAndRefine
from llama_index.core.callbacks import CallbackManager
from llama_index.core.types import TokenAsyncGen, TokenGen

def get_prefix_messages_with_context(context_template: PromptTemplate, system_prompt: str, prefix_messages: List[ChatMessage], chat_history: List[ChatMessage], llm_metadata_system_role: MessageRole) -> List[ChatMessage]:
    ...

def get_response_synthesizer(llm: LLM, callback_manager: CallbackManager, qa_messages: List[ChatMessage], refine_messages: List[ChatMessage], streaming: bool = ..., qa_function_mappings: Optional[Dict[str, Callable]] = ..., refine_function_mappings: Optional[Dict[str, Callable]] = ...) -> CompactAndRefine:
    ...

def response_gen_from_query_engine(response_gen: TokenGen) -> ChatResponseGen:
    ...

async def aresponse_gen_from_query_engine(response_gen: TokenAsyncGen) -> ChatResponseAsyncGen:
    ...

