"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable

from llama_index.core.base.llms.types import (
    ChatMessage,
    ChatResponseAsyncGen,
    ChatResponseGen,
    MessageRole,
)
from llama_index.core.callbacks import CallbackManager
from llama_index.core.llms.llm import LLM
from llama_index.core.prompts import PromptTemplate
from llama_index.core.response_synthesizers import CompactAndRefine
from llama_index.core.types import TokenAsyncGen, TokenGen

def get_prefix_messages_with_context(
    context_template: PromptTemplate,
    system_prompt: str,
    prefix_messages: list[ChatMessage],
    chat_history: list[ChatMessage],
    llm_metadata_system_role: MessageRole,
) -> list[ChatMessage]: ...
def get_response_synthesizer(
    llm: LLM,
    callback_manager: CallbackManager,
    qa_messages: list[ChatMessage],
    refine_messages: list[ChatMessage],
    streaming: bool = ...,
    qa_function_mappings: dict[str, Callable] | None = ...,
    refine_function_mappings: dict[str, Callable] | None = ...,
) -> CompactAndRefine: ...
def response_gen_from_query_engine(response_gen: TokenGen) -> ChatResponseGen: ...
async def aresponse_gen_from_query_engine(response_gen: TokenAsyncGen) -> ChatResponseAsyncGen: ...
