"""check sync

Revision ID: 5485ec4d8be1
Revises: 9384575752e4
Create Date: 2025-07-05 23:51:26.252855

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5485ec4d8be1"
down_revision: str | Sequence[str] | None = "9384575752e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
