"""
This type stub file was generated by pyright.
"""

from collections.abc import Coroutine, Iterable
from typing import Any, TypeVar

"""Async utils."""
dispatcher = ...

def asyncio_module(show_progress: bool = ...) -> Any: ...
def asyncio_run(coro: Coroutine) -> Any:
    """
    Gets an existing event loop to run the coroutine.

    If there is no existing event loop, creates a new one.
    If an event loop is already running, uses threading to run in a separate thread.
    """
    ...

def run_async_tasks(
    tasks: list[Coroutine], show_progress: bool = ..., progress_bar_desc: str = ...
) -> list[Any]:
    """Run a list of async tasks."""
    ...

def chunks(iterable: Iterable, size: int) -> Iterable: ...
async def batch_gather(
    tasks: list[Coroutine], batch_size: int = ..., verbose: bool = ...
) -> list[Any]: ...
def get_asyncio_module(show_progress: bool = ...) -> Any: ...

DEFAULT_NUM_WORKERS = ...
T = TypeVar("T")

@dispatcher.span
async def run_jobs(
    jobs: list[Coroutine[Any, Any, T]],
    show_progress: bool = ...,
    workers: int = ...,
    desc: str | None = ...,
) -> list[T]:
    """
    Run jobs.

    Args:
        jobs (List[Coroutine]):
            List of jobs to run.
        show_progress (bool):
            Whether to show progress bar.

    Returns:
        List[Any]:
            List of results.

    """
    ...
