"""
This type stub file was generated by pyright.
"""

import asyncio
import inspect
import logging
import uuid
import wrapt
from contextlib import contextmanager
from contextvars import Context, ContextVar, Token, copy_context
from functools import partial
from typing import Any, Callable, Dict, Generator, List, Optional, Protocol, TypeVar
from deprecated import deprecated
from pydantic import BaseModel, ConfigDict, Field
from .base import BaseEvent
from .event_handlers import BaseEventHandler
from .events.span import SpanDropEvent
from .span import active_span_id
from .span_handlers import BaseSpanHandler, NullSpanHandler

DISPATCHER_SPAN_DECORATED_ATTR = ...
_logger = ...
active_instrument_tags: ContextVar[Dict[str, Any]] = ...
_R = TypeVar("_R")
@contextmanager
def instrument_tags(new_tags: Dict[str, Any]) -> Generator[None, None, None]:
    ...

class EventDispatcher(Protocol):
    def __call__(self, event: BaseEvent, **kwargs: Any) -> None:
        ...
    


class Dispatcher(BaseModel):
    """
    Dispatcher class.

    Responsible for dispatching BaseEvent (and its subclasses) as well as
    sending signals to enter/exit/drop a BaseSpan. It does so by sending
    event and span signals to its attached BaseEventHandler as well as
    BaseSpanHandler.

    Concurrency:
        - Dispatcher is async-task and thread safe in the sense that
        spans of async coros will maintain its hieararchy or trace-trees and
        spans which emanate from various threads will also maintain its
        hierarchy.
    """
    model_config = ...
    name: str = ...
    event_handlers: List[BaseEventHandler] = ...
    span_handlers: List[BaseSpanHandler] = ...
    parent_name: str = ...
    manager: Optional[Manager] = ...
    root_name: str = ...
    propagate: bool = ...
    current_span_ids: Optional[Dict[Any, str]] = ...
    def __init__(self, name: str = ..., event_handlers: List[BaseEventHandler] = ..., span_handlers: List[BaseSpanHandler] = ..., parent_name: str = ..., manager: Optional[Manager] = ..., root_name: str = ..., propagate: bool = ...) -> None:
        ...
    
    @property
    def parent(self) -> Dispatcher:
        ...
    
    @property
    def root(self) -> Dispatcher:
        ...
    
    def add_event_handler(self, handler: BaseEventHandler) -> None:
        """Add handler to set of handlers."""
        ...
    
    def add_span_handler(self, handler: BaseSpanHandler) -> None:
        """Add handler to set of handlers."""
        ...
    
    def event(self, event: BaseEvent, **kwargs: Any) -> None:
        """Dispatch event to all registered handlers."""
        ...
    
    @deprecated(version="0.10.41", reason="`get_dispatch_event()` has been deprecated in favor of using `event()` directly." " If running into this warning through an integration package, then please " "update your integration to the latest version.")
    def get_dispatch_event(self) -> EventDispatcher:
        """
        Keep for backwards compatibility.

        In llama-index-core v0.10.41, we removed this method and made changes to
        integrations or packs that relied on this method. Adding back this method
        in case any integrations or apps have not been upgraded. That is, they
        still rely on this method.
        """
        ...
    
    def span_enter(self, id_: str, bound_args: inspect.BoundArguments, instance: Optional[Any] = ..., parent_id: Optional[str] = ..., tags: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> None:
        """Send notice to handlers that a span with id_ has started."""
        ...
    
    def span_drop(self, id_: str, bound_args: inspect.BoundArguments, instance: Optional[Any] = ..., err: Optional[BaseException] = ..., **kwargs: Any) -> None:
        """Send notice to handlers that a span with id_ is being dropped."""
        ...
    
    def span_exit(self, id_: str, bound_args: inspect.BoundArguments, instance: Optional[Any] = ..., result: Optional[Any] = ..., **kwargs: Any) -> None:
        """Send notice to handlers that a span with id_ is exiting."""
        ...
    
    def span(self, func: Callable[..., _R]) -> Callable[..., _R]:
        ...
    
    @property
    def log_name(self) -> str:
        """Name to be used in logging."""
        ...
    


class Manager:
    def __init__(self, root: Dispatcher) -> None:
        ...
    
    def add_dispatcher(self, d: Dispatcher) -> None:
        ...
    


