"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from collections.abc import Callable, Generator
from typing import Any, Union

from llama_index.core.base.llms.types import ChatMessage, ChatResponse, CompletionResponse
from llama_index.core.base.response.schema import Response
from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.schema import NodeWithScore, QueryBundle, TextNode

"""Pipeline schema."""
StringableInput = Union[
    CompletionResponse,
    ChatResponse,
    ChatMessage,
    str,
    QueryBundle,
    Response,
    Generator,
    NodeWithScore,
    TextNode,
]

def validate_and_convert_stringable(input: Any) -> str: ...

class InputKeys(BaseModel):
    """Input keys."""

    required_keys: set[str] = ...
    optional_keys: set[str] = ...
    @classmethod
    def from_keys(cls, required_keys: set[str], optional_keys: set[str] | None = ...) -> InputKeys:
        """Create InputKeys from tuple."""
        ...

    def validate_keys(self, input_keys: set[str]) -> None:
        """Validate input keys."""
        ...

    def __len__(self) -> int:
        """Length of input keys."""
        ...

    def all(self) -> set[str]:
        """Get all input keys."""
        ...

class OutputKeys(BaseModel):
    """Output keys."""

    required_keys: set[str] = ...
    @classmethod
    def from_keys(cls, required_keys: set[str]) -> OutputKeys:
        """Create OutputKeys from tuple."""
        ...

    def validate_keys(self, input_keys: set[str]) -> None:
        """Validate input keys."""
        ...

class ChainableMixin(ABC):
    """
    Chainable mixin.

    A module that can produce a `QueryComponent` from a set of inputs through
    `as_query_component`.

    If plugged in directly into a `QueryPipeline`, the `ChainableMixin` will be
    converted into a `QueryComponent` with default parameters.

    """
    def as_query_component(
        self, partial: dict[str, Any] | None = ..., **kwargs: Any
    ) -> QueryComponent:
        """Get query component."""
        ...

class QueryComponent(BaseModel):
    """
    Query component.

    Represents a component that can be run in a `QueryPipeline`.

    """

    partial_dict: dict[str, Any] = ...
    def partial(self, **kwargs: Any) -> None:
        """Update with partial arguments."""
        ...

    @abstractmethod
    def set_callback_manager(self, callback_manager: CallbackManager) -> None:
        """Set callback manager."""
        ...

    @property
    def free_req_input_keys(self) -> set[str]:
        """Get free input keys."""
        ...

    def validate_component_inputs(self, input: dict[str, Any]) -> dict[str, Any]:
        """Validate component inputs."""
        ...

    def validate_component_outputs(self, output: dict[str, Any]) -> dict[str, Any]:
        """Validate component outputs."""
        ...

    def run_component(self, **kwargs: Any) -> dict[str, Any]:
        """Run component."""
        ...

    async def arun_component(self, **kwargs: Any) -> dict[str, Any]:
        """Run component."""
        ...

    @property
    @abstractmethod
    def input_keys(self) -> InputKeys:
        """Input keys."""
        ...

    @property
    @abstractmethod
    def output_keys(self) -> OutputKeys:
        """Output keys."""
        ...

    @property
    def sub_query_components(self) -> list[QueryComponent]:
        """
        Get sub query components.

        Certain query components may have sub query components, e.g. a
        query pipeline will have sub query components, and so will
        an IfElseComponent.

        """
        ...

class CustomQueryComponent(QueryComponent):
    """Custom query component."""

    model_config = ...
    callback_manager: CallbackManager = ...
    def set_callback_manager(self, callback_manager: CallbackManager) -> None:
        """Set callback manager."""
        ...

    @property
    def input_keys(self) -> InputKeys:
        """Input keys."""
        ...

    @property
    def output_keys(self) -> OutputKeys:
        """Output keys."""
        ...

class Link(BaseModel):
    """Link between two components."""

    src: str = ...
    dest: str = ...
    src_key: str | None = ...
    dest_key: str | None = ...
    condition_fn: Callable | None = ...
    input_fn: Callable | None = ...
    def __init__(
        self,
        src: str,
        dest: str,
        src_key: str | None = ...,
        dest_key: str | None = ...,
        condition_fn: Callable | None = ...,
        input_fn: Callable | None = ...,
    ) -> None:
        """Init params."""
        ...

class ComponentIntermediates:
    """Component intermediate inputs and outputs."""
    def __init__(self, inputs: dict[str, Any], outputs: dict[str, Any]) -> None:
        """Initialize."""
        ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

QUERY_COMPONENT_TYPE = Union[QueryComponent, ChainableMixin]
