"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from enum import Enum
from typing import Any, Generic, TypeVar

from llama_index.core.base.llms.types import ChatMessage, ContentBlock
from llama_index.core.bridge.pydantic import BaseModel, model_validator
from llama_index.core.memory.types import BaseMemory
from llama_index.core.prompts import RichPromptTemplate
from llama_index.core.storage.chat_store.sql import MessageStatus, SQLAlchemyChatStore
from sqlalchemy.ext.asyncio import AsyncEngine

T = TypeVar("T", str, list[ContentBlock], list[ChatMessage])
DEFAULT_TOKEN_LIMIT = ...
DEFAULT_FLUSH_SIZE = ...
DEFAULT_MEMORY_BLOCKS_TEMPLATE = ...

class InsertMethod(Enum):
    SYSTEM = ...
    USER = ...

def generate_chat_store_key() -> str:
    """Generate a unique chat store key."""
    ...

def get_default_chat_store() -> SQLAlchemyChatStore:
    """Get the default chat store."""
    ...

class BaseMemoryBlock(BaseModel, Generic[T]):
    """
    A base class for memory blocks.

    Subclasses must implement the `aget` and `aput` methods.
    Optionally, subclasses can implement the `atruncate` method, which is used to reduce the size of the memory block.
    """

    model_config = ...
    name: str = ...
    description: str | None = ...
    priority: int = ...
    accept_short_term_memory: bool = ...
    async def aget(self, messages: list[ChatMessage] | None = ..., **block_kwargs: Any) -> T:
        """
        Pull the memory block (async).

        Returns:
            T: The memory block content. One of:
            - str: A simple text string to be inserted into the template.
            - List[ContentBlock]: A list of content blocks to be inserted into the template.
            - List[ChatMessage]: A list of chat messages to be directly appended to the chat history.

        """
        ...

    async def aput(
        self,
        messages: list[ChatMessage],
        from_short_term_memory: bool = ...,
        session_id: str | None = ...,
    ) -> None:
        """Push to the memory block (async)."""
        ...

    async def atruncate(self, content: T, tokens_to_truncate: int) -> T | None:
        """
        Truncate the memory block content to the given token limit.

        By default, truncation will remove the entire block content.

        Args:
            content:
                The content of type T, depending on what the memory block returns.
            tokens_to_truncate:
                The number of tokens requested to truncate the content by.
                Blocks may or may not truncate to the exact number of tokens requested, but it
                can be used as a hint for the block to truncate.

        Returns:
            The truncated content of type T, or None if the content is completely truncated.

        """
        ...

class Memory(BaseMemory):
    """
    A memory module that waterfalls into memory blocks.

    Works by orchestrating around
    - a FIFO queue of messages
    - a list of memory blocks
    - various parameters (pressure size, token limit, etc.)

    When the FIFO queue reaches the token limit, the oldest messages within the pressure size are ejected from the FIFO queue.
    The messages are then processed by each memory block.

    When pulling messages from this memory, the memory blocks are processed in order, and the messages are injected into the system message or the latest user message.
    """

    model_config = ...
    token_limit: int = ...
    token_flush_size: int = ...
    chat_history_token_ratio: float = ...
    memory_blocks: list[BaseMemoryBlock] = ...
    memory_blocks_template: RichPromptTemplate = ...
    insert_method: InsertMethod = ...
    image_token_size_estimate: int = ...
    audio_token_size_estimate: int = ...
    tokenizer_fn: Callable[[str], list] = ...
    sql_store: SQLAlchemyChatStore = ...
    session_id: str = ...
    @classmethod
    def class_name(cls) -> str: ...
    @model_validator(mode="before")
    @classmethod
    def validate_memory(cls, values: dict) -> dict: ...
    @classmethod
    def from_defaults(
        cls,
        session_id: str | None = ...,
        chat_history: list[ChatMessage] | None = ...,
        token_limit: int = ...,
        memory_blocks: list[BaseMemoryBlock[Any]] | None = ...,
        tokenizer_fn: Callable[[str], list] | None = ...,
        chat_history_token_ratio: float = ...,
        token_flush_size: int = ...,
        memory_blocks_template: RichPromptTemplate = ...,
        insert_method: InsertMethod = ...,
        image_token_size_estimate: int = ...,
        audio_token_size_estimate: int = ...,
        table_name: str = ...,
        async_database_uri: str | None = ...,
        async_engine: AsyncEngine | None = ...,
    ) -> Memory:
        """Initialize Memory."""
        ...

    async def aget(
        self, input: str | ChatMessage | None = ..., **block_kwargs: Any
    ) -> list[ChatMessage]:
        """Get messages with memory blocks included (async)."""
        ...

    async def aput(self, message: ChatMessage) -> None:
        """Add a message to the chat store and process waterfall logic if needed."""
        ...

    async def aput_messages(self, messages: list[ChatMessage]) -> None:
        """Add a list of messages to the chat store and process waterfall logic if needed."""
        ...

    async def aset(self, messages: list[ChatMessage]) -> None:
        """Set the chat history."""
        ...

    async def aget_all(self, status: MessageStatus | None = ...) -> list[ChatMessage]:
        """Get all messages."""
        ...

    async def areset(self, status: MessageStatus | None = ...) -> None:
        """Reset the memory."""
        ...

    def get(self, input: str | ChatMessage | None = ..., **block_kwargs: Any) -> list[ChatMessage]:
        """Get messages with memory blocks included."""
        ...

    def get_all(self, status: MessageStatus | None = ...) -> list[ChatMessage]:
        """Get all messages."""
        ...

    def put(self, message: ChatMessage) -> None:
        """Add a message to the chat store and process waterfall logic if needed."""
        ...

    def set(self, messages: list[ChatMessage]) -> None:
        """Set the chat history."""
        ...

    def reset(self) -> None:
        """Reset the memory."""
        ...
