"""
This type stub file was generated by pyright.
"""

import os
from typing import ClassVar, cast
from chromadb.telemetry.product import ProductTelemetryEvent

class ClientStartEvent(ProductTelemetryEvent):
    def __init__(self) -> None:
        ...
    


class ServerStartEvent(ProductTelemetryEvent):
    is_cli: bool
    def __init__(self) -> None:
        ...
    


class ClientCreateCollectionEvent(ProductTelemetryEvent):
    collection_uuid: str
    def __init__(self, collection_uuid: str) -> None:
        ...
    


class CollectionAddEvent(ProductTelemetryEvent):
    max_batch_size: ClassVar[int] = ...
    batch_size: int
    collection_uuid: str
    add_amount: int
    with_documents: int
    with_metadata: int
    with_uris: int
    def __init__(self, collection_uuid: str, add_amount: int, with_documents: int, with_metadata: int, with_uris: int, batch_size: int = ...) -> None:
        ...
    
    @property
    def batch_key(self) -> str:
        ...
    
    def batch(self, other: ProductTelemetryEvent) -> CollectionAddEvent:
        ...
    


class CollectionUpdateEvent(ProductTelemetryEvent):
    max_batch_size: ClassVar[int] = ...
    batch_size: int
    collection_uuid: str
    update_amount: int
    with_embeddings: int
    with_metadata: int
    with_documents: int
    with_uris: int
    def __init__(self, collection_uuid: str, update_amount: int, with_embeddings: int, with_metadata: int, with_documents: int, with_uris: int, batch_size: int = ...) -> None:
        ...
    
    @property
    def batch_key(self) -> str:
        ...
    
    def batch(self, other: ProductTelemetryEvent) -> CollectionUpdateEvent:
        ...
    


class CollectionQueryEvent(ProductTelemetryEvent):
    max_batch_size: ClassVar[int] = ...
    batch_size: int
    collection_uuid: str
    query_amount: int
    filtered_ids_amount: int
    with_metadata_filter: int
    with_document_filter: int
    n_results: int
    include_metadatas: int
    include_documents: int
    include_uris: int
    include_distances: int
    def __init__(self, collection_uuid: str, query_amount: int, filtered_ids_amount: int, with_metadata_filter: int, with_document_filter: int, n_results: int, include_metadatas: int, include_documents: int, include_uris: int, include_distances: int, batch_size: int = ...) -> None:
        ...
    
    @property
    def batch_key(self) -> str:
        ...
    
    def batch(self, other: ProductTelemetryEvent) -> CollectionQueryEvent:
        ...
    


class CollectionGetEvent(ProductTelemetryEvent):
    max_batch_size: ClassVar[int] = ...
    batch_size: int
    collection_uuid: str
    ids_count: int
    limit: int
    include_metadata: int
    include_documents: int
    include_uris: int
    def __init__(self, collection_uuid: str, ids_count: int, limit: int, include_metadata: int, include_documents: int, include_uris: int, batch_size: int = ...) -> None:
        ...
    
    @property
    def batch_key(self) -> str:
        ...
    
    def batch(self, other: ProductTelemetryEvent) -> CollectionGetEvent:
        ...
    


class CollectionDeleteEvent(ProductTelemetryEvent):
    collection_uuid: str
    delete_amount: int
    def __init__(self, collection_uuid: str, delete_amount: int) -> None:
        ...
    


