"""
This type stub file was generated by pyright.
"""

def strtobool(val: str) -> bool:
    """
    Convert a string representation of truth to True or False.

    True values are 'y', 'yes', 't', 'true', 'on', and '1'; false values
    are 'n', 'no', 'f', 'false', 'off', and '0'.  Raises ValueError if
    'val' is anything else.
    """
    ...

def generate_canary_word(prefix: str = ..., suffix: str = ..., token_length: int = ...) -> str: ...
def python_type_to_jsonschema(python_type: type) -> str:
    """Given a Python type, returns the jsonschema string describing it."""
    ...

def parse_params_from_docstring(docstring: str) -> dict[str, dict[str, str]]: ...
