from typing import IO, Any, Optional, Union

class AudioSegment:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def from_file(
        cls,
        file: Union[str, IO[bytes]],
        format: Optional[str] = ...,
        codec: Optional[str] = ...,
        parameters: Optional[list[str]] = ...,
    ) -> "AudioSegment": ...
    @classmethod
    def silent(cls, duration: int = ..., frame_rate: int = ...) -> "AudioSegment": ...
    def export(
        self, out_f: str, format: Optional[str] = ..., **kwargs: Any
    ) -> None: ...
    def __len__(self) -> int: ...
    def __add__(self, other: "AudioSegment") -> "AudioSegment": ...
    def __getitem__(self, key: slice) -> "AudioSegment": ...
