from typing import IO, Any

class AudioSegment:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def from_file(
        cls,
        file: str | IO[bytes],
        format: str | None = ...,
        codec: str | None = ...,
        parameters: list[str] | None = ...,
    ) -> AudioSegment: ...
    @classmethod
    def silent(cls, duration: int = ..., frame_rate: int = ...) -> AudioSegment: ...
    def export(self, out_f: str, format: str | None = ..., **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def __add__(self, other: AudioSegment) -> AudioSegment: ...
    def __getitem__(self, key: slice) -> AudioSegment: ...
