"""
This type stub file was generated by pyright.
"""

import cv2.mat_wrapper
import cv2.gapi.wip.draw
import cv2
import typing as _typing
import numpy
import cv2.dnn

__all__ = ["IntPointer", "MatLike", "MatShape", "Size", "Size2f", "Scalar", "Point", "Point2i", "Point2f", "Point2d", "Point3i", "Point3f", "Point3d", "Range", "Rect", "Rect2i", "Rect2f", "Rect2d", "Moments", "RotatedRect", "TermCriteria", "Vec2i", "Vec2f", "Vec2d", "Vec3i", "Vec3f", "Vec3d", "Vec4i", "Vec4f", "Vec4d", "Vec6f", "FeatureDetector", "DescriptorExtractor", "FeatureExtractor", "Matx33f", "Matx33d", "Matx44f", "Matx44d", "LayerId", "LayerParams", "IndexParams", "SearchParams", "map_string_and_string", "map_string_and_int", "map_string_and_vector_size_t", "map_string_and_vector_float", "map_int_and_double", "GProtoArg", "GProtoInputArgs", "GProtoOutputArgs", "GRunArg", "GOptRunArg", "GMetaArg", "Prim", "GTypeInfo", "ExtractArgsCallback", "ExtractMetaCallback"]
if _typing.TYPE_CHECKING:
    NumPyArrayNumeric = numpy.ndarray[_typing.Any, numpy.dtype[numpy.integer[_typing.Any] | numpy.floating[_typing.Any]]]
else:
    ...
if _typing.TYPE_CHECKING:
    NumPyArrayFloat32 = numpy.ndarray[_typing.Any, numpy.dtype[numpy.float32]]
else:
    ...
if _typing.TYPE_CHECKING:
    NumPyArrayFloat64 = numpy.ndarray[_typing.Any, numpy.dtype[numpy.float64]]
else:
    ...
if _typing.TYPE_CHECKING:
    TermCriteria_Type = cv2.TermCriteria_Type
else:
    ...
IntPointer = int
MatLike = _typing.Union[cv2.mat_wrapper.Mat, NumPyArrayNumeric]
MatShape = _typing.Sequence[int]
Size = _typing.Sequence[int]
Size2f = _typing.Sequence[float]
Scalar = _typing.Sequence[float]
Point = _typing.Sequence[int]
Point2i = Point
Point2f = _typing.Sequence[float]
Point2d = _typing.Sequence[float]
Point3i = _typing.Sequence[int]
Point3f = _typing.Sequence[float]
Point3d = _typing.Sequence[float]
Range = _typing.Sequence[int]
Rect = _typing.Sequence[int]
Rect2i = _typing.Sequence[int]
Rect2f = _typing.Sequence[float]
Rect2d = _typing.Sequence[float]
Moments = _typing.Dict[str, float]
RotatedRect = _typing.Tuple[Point2f, Size2f, float]
TermCriteria = _typing.Tuple[TermCriteria_Type, int, float]
Vec2i = _typing.Sequence[int]
Vec2f = _typing.Sequence[float]
Vec2d = _typing.Sequence[float]
Vec3i = _typing.Sequence[int]
Vec3f = _typing.Sequence[float]
Vec3d = _typing.Sequence[float]
Vec4i = _typing.Sequence[int]
Vec4f = _typing.Sequence[float]
Vec4d = _typing.Sequence[float]
Vec6f = _typing.Sequence[float]
FeatureDetector = cv2.Feature2D
DescriptorExtractor = cv2.Feature2D
FeatureExtractor = cv2.Feature2D
Matx33f = NumPyArrayFloat32
Matx33d = NumPyArrayFloat64
Matx44f = NumPyArrayFloat32
Matx44d = NumPyArrayFloat64
LayerId = cv2.dnn.DictValue
LayerParams = _typing.Dict[str, _typing.Union[int, float, str]]
IndexParams = _typing.Dict[str, _typing.Union[bool, int, float, str]]
SearchParams = _typing.Dict[str, _typing.Union[bool, int, float, str]]
map_string_and_string = _typing.Dict[str, str]
map_string_and_int = _typing.Dict[str, int]
map_string_and_vector_size_t = _typing.Dict[str, _typing.Sequence[int]]
map_string_and_vector_float = _typing.Dict[str, _typing.Sequence[float]]
map_int_and_double = _typing.Dict[int, float]
GProtoArg = _typing.Union[Scalar, cv2.GMat, cv2.GOpaqueT, cv2.GArrayT]
GProtoInputArgs = _typing.Sequence[GProtoArg]
GProtoOutputArgs = _typing.Sequence[GProtoArg]
GRunArg = _typing.Union[MatLike, Scalar, cv2.GOpaqueT, cv2.GArrayT, _typing.Sequence[_typing.Any], None]
GOptRunArg = _typing.Optional[GRunArg]
GMetaArg = _typing.Union[cv2.GMat, Scalar, cv2.GOpaqueT, cv2.GArrayT]
Prim = _typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
GTypeInfo = _typing.Union[cv2.GMat, Scalar, cv2.GOpaqueT, cv2.GArrayT]
ExtractArgsCallback = _typing.Callable[[_typing.Sequence[GTypeInfo]], _typing.Sequence[GRunArg]]
ExtractMetaCallback = _typing.Callable[[_typing.Sequence[GTypeInfo]], _typing.Sequence[GMetaArg]]
