"""
This type stub file was generated by pyright.
"""

from typing import Any

from torchgen.model import (
    Annotation,
    Argument,
    BaseType,
    CustomClassType,
    FunctionSchema,
    ListType,
    Return,
)

class TypeGen:
    convert_to_base_ty = ...
    @staticmethod
    def from_example(obj: Any) -> BaseType | ListType | CustomClassType: ...

class ReturnGen:
    @staticmethod
    def from_example(name: str | None, obj: Any, annotation: Annotation | None) -> Return: ...

class ArgumentGen:
    @staticmethod
    def from_example(
        name: str, obj: Any, default: str | None, annotation: Annotation | None
    ) -> Argument: ...

class FunctionSchemaGen:
    @staticmethod
    def from_example(
        op_name: str, example_inputs: tuple[tuple[str, Any], ...], example_outputs: tuple[Any, ...]
    ) -> FunctionSchema: ...
