"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Union
from torchgen.model import Annotation, Argument, Arguments, BaseOperatorName, BaseTy, BaseType, CustomClassType, FunctionSchema, ListType, OperatorName, Return

class TypeGen:
    convert_to_base_ty = ...
    @staticmethod
    def from_example(obj: Any) -> Union[BaseType, ListType, CustomClassType]:
        ...
    


class ReturnGen:
    @staticmethod
    def from_example(name: Optional[str], obj: Any, annotation: Optional[Annotation]) -> Return:
        ...
    


class ArgumentGen:
    @staticmethod
    def from_example(name: str, obj: Any, default: Optional[str], annotation: Optional[Annotation]) -> Argument:
        ...
    


class FunctionSchemaGen:
    @staticmethod
    def from_example(op_name: str, example_inputs: tuple[tuple[str, Any], ...], example_outputs: tuple[Any, ...]) -> FunctionSchema:
        ...
    


