services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: wintermute_pg
    restart: always
    environment:
      POSTGRES_USER: wintermute
      POSTGRES_PASSWORD: wintermute
      POSTGRES_DB: wintermute
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
