"""
This type stub file was generated by pyright.
"""

import abc
import collections
import itertools
import torch
from torch.nn.modules.module import _addindent

__all__ = ["WeightedQuantizedModule"]
class WeightedQuantizedModule(torch.nn.Module, metaclass=abc.ABCMeta):
    """Wrapper for quantized modules than can be lowered from reference modules."""
    @classmethod
    @abc.abstractmethod
    def from_reference(cls, ref_module, output_scale, output_zero_point):
        ...
    


_pair_from_first = ...
