"""
This type stub file was generated by pyright.
"""

import functools
import logging
import torch
from typing import Optional
from ... import config

log = ...
def get_cuda_arch() -> Optional[str]:
    ...

def get_cuda_version() -> Optional[str]:
    ...

@functools.lru_cache(None)
def nvcc_exist(nvcc_path: str = ...) -> bool:
    ...

