"""
This type stub file was generated by pyright.
"""

import types
import typing

"""
Backport Python3.8+ typing utils &amp; issubtype &amp; more

![Python 3.6](https://github.com/bojiang/typing_utils/workflows/Python%203.6/badge.svg)
![Python 3.7](https://github.com/bojiang/typing_utils/workflows/Python%203.7/badge.svg)
![Python 3.8](https://github.com/bojiang/typing_utils/workflows/Python%203.8/badge.svg)

## Install

``` bash
    pip install typing_utils
```
"""
if hasattr(typing, "ForwardRef"):
    ForwardRef = ...
else:
    ForwardRef = ...
if hasattr(typing, "Literal"):
    Literal = ...
else:
    Literal = ...
if hasattr(typing, "_TypedDictMeta"):
    _TypedDictMeta = ...
else:
    _TypedDictMeta = ...
if hasattr(types, "UnionType"):
    UnionType = ...
else:
    UnionType = ...
unknown = ...
BUILTINS_MAPPING = ...
STATIC_SUBTYPE_MAPPING: dict[type, type] = ...
if UnionType:
    def is_union(element: object) -> bool: ...

else:
    def is_union(element: object) -> bool: ...

def optional_all(elements) -> bool | None: ...
def optional_any(elements) -> bool | None: ...

get_type_hints = ...
GenericClass = ...
UnionClass = ...
Type = typing.Union[None, type, "typing.TypeVar"]
OriginType = typing.Union[None, type]
TypeArgs = typing.Union[type, typing.AbstractSet[type], typing.Sequence[type]]

def get_origin(type_):  # -> Type:
    """Get the unsubscripted version of a type.
    This supports generic types, Callable, Tuple, Union, Literal, Final and ClassVar.
    Return None for unsupported types.

    Examples:

    ```python
        from typing_utils import get_origin

        get_origin(Literal[42]) is Literal
        get_origin(int) is None
        get_origin(ClassVar[int]) is ClassVar
        get_origin(Generic) is Generic
        get_origin(Generic[T]) is Generic
        get_origin(Union[T, int]) is Union
        get_origin(List[Tuple[T, T]][int]) == list
    ```
    """
    ...

def get_args(type_) -> tuple:
    """Get type arguments with all substitutions performed.
    For unions, basic simplifications used by Union constructor are performed.

    Examples:

    ```python
        from typing_utils import get_args

        get_args(Dict[str, int]) == (str, int)
        get_args(int) == ()
        get_args(Union[int, Union[T, int], str][int]) == (int, str)
        get_args(Union[int, Tuple[T, int]][str]) == (int, Tuple[str, int])
        get_args(Callable[[], T][int]) == ([], int)
    ```
    """
    ...

def eval_forward_ref(ref, forward_refs=...):  # -> Any:
    """
    eval forward_refs in all cPython versions
    """
    ...

class NormalizedType(typing.NamedTuple):
    """
    Normalized type, made it possible to compare, hash between types.
    """

    origin: Type
    args: tuple | frozenset = ...
    def __eq__(self, other) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self):  # -> str:
        ...

def normalize(type_: Type) -> NormalizedType:
    """
    convert types to NormalizedType instances.
    """
    ...

NormalizedTypeArgs = typing.Union[
    tuple[typing.Any, ...],
    frozenset[NormalizedType],
    NormalizedType,
]

def issubtype(left: Type, right: Type, forward_refs: dict | None = ...) -> bool | None:
    """Check that the left argument is a subtype of the right.
    For unions, check if the type arguments of the left is a subset of the right.
    Also works for nested types including ForwardRefs.

    Examples:

    ```python
        from typing_utils import issubtype

        issubtype(typing.List, typing.Any) == True
        issubtype(list, list) == True
        issubtype(list, typing.List) == True
        issubtype(list, typing.Sequence) == True
        issubtype(typing.List[int], list) == True
        issubtype(typing.List[typing.List], list) == True
        issubtype(list, typing.List[int]) == False
        issubtype(list, typing.Union[typing.Tuple, typing.Set]) == False
        issubtype(typing.List[typing.List], typing.List[typing.Sequence]) == True
        JSON = typing.Union[
            int, float, bool, str, None, typing.Sequence["JSON"],
            typing.Mapping[str, "JSON"]
        ]
        issubtype(str, JSON, forward_refs={'JSON': JSON}) == True
        issubtype(typing.Dict[str, str], JSON, forward_refs={'JSON': JSON}) == True
        issubtype(typing.Dict[str, bytes], JSON, forward_refs={'JSON': JSON}) == False
    ```
    """
    ...

__all__ = ["issubtype", "get_origin", "get_args", "get_type_hints"]
