"""
This type stub file was generated by pyright.
"""

import json
from abc import abstractmethod
from overrides import override
from typing import Any, ClassVar, Dict, List, Optional, Protocol, TypeVar, Union, cast
from typing_extensions import Self
from multiprocessing import cpu_count
from chromadb.serde import JSONSerializable

class StaticParameterError(Exception):
    """Represents an error that occurs when a static parameter is set."""
    ...


class InvalidConfigurationError(ValueError):
    """Represents an error that occurs when a configuration is invalid."""
    ...


ParameterValue = Union[str, int, float, bool, "ConfigurationInternal"]
class ParameterValidator(Protocol):
    """Represents an abstract parameter validator."""
    @abstractmethod
    def __call__(self, value: ParameterValue) -> bool:
        """Returns whether the given value is valid."""
        ...
    


class ConfigurationDefinition:
    """Represents the definition of a configuration."""
    name: str
    validator: ParameterValidator
    is_static: bool
    default_value: ParameterValue
    def __init__(self, name: str, validator: ParameterValidator, is_static: bool, default_value: ParameterValue) -> None:
        ...
    


class ConfigurationParameter:
    """Represents a parameter of a configuration."""
    name: str
    value: ParameterValue
    def __init__(self, name: str, value: ParameterValue) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, __value: object) -> bool:
        ...
    


T = TypeVar("T", bound="ConfigurationInternal")
class ConfigurationInternal(JSONSerializable["ConfigurationInternal"]):
    """Represents an abstract configuration, used internally by Chroma."""
    parameter_map: Dict[str, ConfigurationParameter]
    definitions: ClassVar[Dict[str, ConfigurationDefinition]]
    def __init__(self, parameters: Optional[List[ConfigurationParameter]] = ...) -> None:
        """Initializes a new instance of the Configuration class. Respecting defaults and
        validators."""
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, __value: object) -> bool:
        ...
    
    @abstractmethod
    def configuration_validator(self) -> None:
        """Perform custom validation when parameters are dependent on each other.

        Raises an InvalidConfigurationError if the configuration is invalid.
        """
        ...
    
    def get_parameters(self) -> List[ConfigurationParameter]:
        """Returns the parameters of the configuration."""
        ...
    
    def get_parameter(self, name: str) -> ConfigurationParameter:
        """Returns the parameter with the given name, or except if it doesn't exist."""
        ...
    
    def set_parameter(self, name: str, value: Union[str, int, float, bool]) -> None:
        """Sets the parameter with the given name to the given value."""
        ...
    
    @override
    def to_json_str(self) -> str:
        """Returns the JSON representation of the configuration."""
        ...
    
    @classmethod
    @override
    def from_json_str(cls, json_str: str) -> Self:
        """Returns a configuration from the given JSON string."""
        ...
    
    @override
    def to_json(self) -> Dict[str, Any]:
        """Returns the JSON compatible dictionary representation of the configuration."""
        ...
    
    @classmethod
    @override
    def from_json(cls, json_map: Dict[str, Any]) -> Self:
        """Returns a configuration from the given JSON string."""
        ...
    


class HNSWConfigurationInternal(ConfigurationInternal):
    """Internal representation of the HNSW configuration.
    Used for validation, defaults, serialization and deserialization."""
    definitions = ...
    @override
    def configuration_validator(self) -> None:
        ...
    
    @classmethod
    def from_legacy_params(cls, params: Dict[str, Any]) -> Self:
        """Returns an HNSWConfiguration from a metadata dict containing legacy HNSW parameters. Used for migration."""
        ...
    


class HNSWConfigurationInterface(HNSWConfigurationInternal):
    """HNSW index configuration parameters.
    See https://docs.trychroma.com/guides#changing-the-distance-function for more information.
    """
    def __init__(self, space: str = ..., ef_construction: int = ..., ef_search: int = ..., num_threads: int = ..., M: int = ..., resize_factor: float = ..., batch_size: int = ..., sync_threshold: int = ...) -> None:
        ...
    


HNSWConfiguration = HNSWConfigurationInterface
class CollectionConfigurationInternal(ConfigurationInternal):
    """Internal representation of the collection configuration.
    Used for validation, defaults, and serialization / deserialization."""
    definitions = ...
    @override
    def configuration_validator(self) -> None:
        ...
    


class CollectionConfigurationInterface(CollectionConfigurationInternal):
    """Configuration parameters for creating a collection."""
    def __init__(self, hnsw_configuration: Optional[HNSWConfigurationInternal]) -> None:
        """Initializes a new instance of the CollectionConfiguration class.
        Args:
            hnsw_configuration: The HNSW configuration to use for the collection.
        """
        ...
    


CollectionConfiguration = CollectionConfigurationInterface
class EmbeddingsQueueConfigurationInternal(ConfigurationInternal):
    definitions = ...
    @override
    def configuration_validator(self) -> None:
        ...
    


