"""
This type stub file was generated by pyright.
"""

"""
Schema Registry for Embedding Functions

This module provides a registry of all available schemas for embedding functions.
It can be used to get information about available schemas and their versions.
"""

def get_available_schemas() -> list[str]:
    """
    Get a list of all available schemas.

    Returns:
        A list of schema names (without .json extension)
    """
    ...

def get_schema_info() -> dict[str, dict[str, str]]:
    """
    Get information about all available schemas.

    Returns:
        A dictionary mapping schema names to information about the schema
    """
    ...

def get_embedding_function_names() -> set[str]:
    """
    Get a set of all embedding function names that have schemas.

    Returns:
        A set of embedding function names
    """
    ...
