"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import TYPE_CHECKING, Any

from llama_index.core.agent.runner.base import AgentRunner
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.llms.types import ChatMessage
from llama_index.core.bridge.pydantic import BaseModel, SerializeAsAny
from llama_index.core.callbacks import CallbackManager
from llama_index.core.chat_engine.types import BaseChatEngine, StreamingAgentChatResponse
from llama_index.core.instrumentation import DispatcherSpanMixin
from llama_index.core.memory.types import BaseMemory
from llama_index.core.prompts.mixin import PromptMixin

"""Base agent type."""
if TYPE_CHECKING: ...

class BaseAgent(BaseChatEngine, BaseQueryEngine):
    """Base Agent."""
    def stream_chat(
        self, message: str, chat_history: list[ChatMessage] | None = ...
    ) -> StreamingAgentChatResponse: ...
    async def astream_chat(
        self, message: str, chat_history: list[ChatMessage] | None = ...
    ) -> StreamingAgentChatResponse: ...

class TaskStep(BaseModel):
    """
    Agent task step.

    Represents a single input step within the execution run ("Task") of an agent
    given a user input.

    The output is returned as a `TaskStepOutput`.

    """

    task_id: str = ...
    step_id: str = ...
    input: str | None = ...
    step_state: dict[str, Any] = ...
    next_steps: dict[str, TaskStep] = ...
    prev_steps: dict[str, TaskStep] = ...
    is_ready: bool = ...
    def get_next_step(
        self, step_id: str, input: str | None = ..., step_state: dict[str, Any] | None = ...
    ) -> TaskStep:
        """
        Convenience function to get next step.

        Preserve task_id, memory, step_state.

        """
        ...

    def link_step(self, next_step: TaskStep) -> None:
        """
        Link to next step.

        Add link from this step to next, and from next step to current.

        """
        ...

class TaskStepOutput(BaseModel):
    """Agent task step output."""

    output: Any = ...
    task_step: TaskStep = ...
    next_steps: list[TaskStep] = ...
    is_last: bool = ...
    def __str__(self) -> str:
        """String representation."""
        ...

class Task(BaseModel):
    """
    Agent Task.

    Represents a "run" of an agent given a user input.

    """

    model_config = ...
    task_id: str = ...
    input: str = ...
    memory: SerializeAsAny[BaseMemory] = ...
    callback_manager: CallbackManager = ...
    extra_state: dict[str, Any] = ...

class BaseAgentWorker(PromptMixin, DispatcherSpanMixin):
    """Base agent worker."""
    @abstractmethod
    def initialize_step(self, task: Task, **kwargs: Any) -> TaskStep:
        """Initialize step from task."""
        ...

    @abstractmethod
    def run_step(self, step: TaskStep, task: Task, **kwargs: Any) -> TaskStepOutput:
        """Run step."""
        ...

    @abstractmethod
    async def arun_step(self, step: TaskStep, task: Task, **kwargs: Any) -> TaskStepOutput:
        """Run step (async)."""
        ...

    @abstractmethod
    def stream_step(self, step: TaskStep, task: Task, **kwargs: Any) -> TaskStepOutput:
        """Run step (stream)."""
        ...

    @abstractmethod
    async def astream_step(self, step: TaskStep, task: Task, **kwargs: Any) -> TaskStepOutput:
        """Run step (async stream)."""
        ...

    @abstractmethod
    def finalize_task(self, task: Task, **kwargs: Any) -> None:
        """Finalize task, after all the steps are completed."""
        ...

    async def afinalize_task(self, task: Task, **kwargs: Any) -> None:
        """Finalize task, after all the steps are completed."""
        ...

    def set_callback_manager(self, callback_manager: CallbackManager) -> None:
        """Set callback manager."""
        ...

    def as_agent(self, **kwargs: Any) -> AgentRunner:
        """Return as an agent runner."""
        ...
