"""
This type stub file was generated by pyright.
"""

import warnings
import numpy as np
import scipy.special
from scipy.linalg._matfuncs_sqrtm import SqrtmError, _sqrtm_triu
from scipy.linalg._decomp_schur import rsf2csf, schur
from scipy.linalg._matfuncs import funm
from scipy.linalg import solve_triangular, svdvals
from scipy.sparse.linalg._interface import LinearOperator
from scipy.sparse.linalg import onenormest

"""
Matrix functions that use Pade approximation with inverse scaling and squaring.

"""
class LogmRankWarning(UserWarning):
    ...


class LogmExactlySingularWarning(LogmRankWarning):
    ...


class LogmNearlySingularWarning(LogmRankWarning):
    ...


class LogmError(np.linalg.LinAlgError):
    ...


class FractionalMatrixPowerError(np.linalg.LinAlgError):
    ...


class _MatrixM1PowerOperator(LinearOperator):
    """
    A representation of the linear operator (A - I)^p.
    """
    def __init__(self, A, p) -> None:
        ...
    


