"""
This type stub file was generated by pyright.
"""

from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.bridge.langchain import BaseTool
from llama_index.core.bridge.pydantic import BaseModel

"""LlamaIndex Tool classes."""

class IndexToolConfig(BaseModel):
    """Configuration for LlamaIndex index tool."""

    model_config = ...
    query_engine: BaseQueryEngine
    name: str
    description: str
    tool_kwargs: dict = ...

class LlamaIndexTool(BaseTool):
    """Tool for querying a LlamaIndex."""

    query_engine: BaseQueryEngine
    return_sources: bool = ...
    @classmethod
    def from_tool_config(cls, tool_config: IndexToolConfig) -> LlamaIndexTool:
        """Create a tool from a tool config."""
        ...
