"""
This type stub file was generated by pyright.
"""

import json
from collections.abc import Callable
from typing import Any, ClassVar

class FilesystemJSONEncoder(json.JSONEncoder):
    include_password: ClassVar[bool] = ...
    def default(self, o: Any) -> Any: ...
    def make_serializable(self, obj: Any) -> Any:
        """
        Recursively converts an object so that it can be JSON serialized via
        :func:`json.dumps` and :func:`json.dump`, without actually calling
        said functions.
        """
        ...

class FilesystemJSONDecoder(json.JSONDecoder):
    def __init__(
        self,
        *,
        object_hook: Callable[[dict[str, Any]], Any] | None = ...,
        parse_float: Callable[[str], Any] | None = ...,
        parse_int: Callable[[str], Any] | None = ...,
        parse_constant: Callable[[str], Any] | None = ...,
        strict: bool = ...,
        object_pairs_hook: Callable[[list[tuple[str, Any]]], Any] | None = ...,
    ) -> None: ...
    @classmethod
    def try_resolve_path_cls(cls, dct: dict[str, Any]):  # -> type[PurePath] | None:
        ...
    @classmethod
    def try_resolve_fs_cls(cls, dct: dict[str, Any]):  # -> type[AbstractFileSystem] | type | None:
        ...
    def custom_object_hook(
        self, dct: dict[str, Any]
    ):  # -> AbstractFileSystem | PurePath | Any | Dict[str, Any]:
        ...
    def unmake_serializable(self, obj: Any) -> Any:
        """
        Inverse function of :meth:`FilesystemJSONEncoder.make_serializable`.
        """
        ...
