"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple
from chromadb.auth import UserIdentity
from chromadb.config import DEFAULT_DATABASE, DEFAULT_TENANT
from chromadb.errors import ChromaAuthError

def maybe_set_tenant_and_database(user_identity: UserIdentity, overwrite_singleton_tenant_database_access_from_auth: bool, user_provided_tenant: Optional[str] = ..., user_provided_database: Optional[str] = ...) -> Tuple[Optional[str], Optional[str]]:
    ...

