"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING, Union
from chromadb.api.types import CollectionMetadata, Document, Embedding, GetResult, ID, IDs, Image, Include, Metadata, OneOrMany, PyEmbedding, QueryResult, URI, Where, WhereDocument
from chromadb.api.models.CollectionCommon import CollectionCommon
from chromadb.api.collection_configuration import UpdateCollectionConfiguration
from chromadb.api import AsyncServerAPI

if TYPE_CHECKING:
    ...
class AsyncCollection(CollectionCommon["AsyncServerAPI"]):
    async def add(self, ids: OneOrMany[ID], embeddings: Optional[Union[OneOrMany[Embedding], OneOrMany[PyEmbedding],]] = ..., metadatas: Optional[OneOrMany[Metadata]] = ..., documents: Optional[OneOrMany[Document]] = ..., images: Optional[OneOrMany[Image]] = ..., uris: Optional[OneOrMany[URI]] = ...) -> None:
        """Add embeddings to the data store.
        Args:
            ids: The ids of the embeddings you wish to add
            embeddings: The embeddings to add. If None, embeddings will be computed based on the documents or images using the embedding_function set for the Collection. Optional.
            metadatas: The metadata to associate with the embeddings. When querying, you can filter on this metadata. Optional.
            documents: The documents to associate with the embeddings. Optional.
            images: The images to associate with the embeddings. Optional.
            uris: The uris of the images to associate with the embeddings. Optional.

        Returns:
            None

        Raises:
            ValueError: If you don't provide either embeddings or documents
            ValueError: If the length of ids, embeddings, metadatas, or documents don't match
            ValueError: If you don't provide an embedding function and don't provide embeddings
            ValueError: If you provide both embeddings and documents
            ValueError: If you provide an id that already exists

        """
        ...
    
    async def count(self) -> int:
        """The total number of embeddings added to the database

        Returns:
            int: The total number of embeddings added to the database

        """
        ...
    
    async def get(self, ids: Optional[OneOrMany[ID]] = ..., where: Optional[Where] = ..., limit: Optional[int] = ..., offset: Optional[int] = ..., where_document: Optional[WhereDocument] = ..., include: Include = ...) -> GetResult:
        """Get embeddings and their associate data from the data store. If no ids or where filter is provided returns
        all embeddings up to limit starting at offset.

        Args:
            ids: The ids of the embeddings to get. Optional.
            where: A Where type dict used to filter results by. E.g. `{"$and": [{"color" : "red"}, {"price": {"$gte": 4.20}}]}`. Optional.
            limit: The number of documents to return. Optional.
            offset: The offset to start returning results from. Useful for paging results with limit. Optional.
            where_document: A WhereDocument type dict used to filter by the documents. E.g. `{"$contains": "hello"}`. Optional.
            include: A list of what to include in the results. Can contain `"embeddings"`, `"metadatas"`, `"documents"`. Ids are always included. Defaults to `["metadatas", "documents"]`. Optional.

        Returns:
            GetResult: A GetResult object containing the results.

        """
        ...
    
    async def peek(self, limit: int = ...) -> GetResult:
        """Get the first few results in the database up to limit

        Args:
            limit: The number of results to return.

        Returns:
            GetResult: A GetResult object containing the results.
        """
        ...
    
    async def query(self, query_embeddings: Optional[Union[OneOrMany[Embedding], OneOrMany[PyEmbedding],]] = ..., query_texts: Optional[OneOrMany[Document]] = ..., query_images: Optional[OneOrMany[Image]] = ..., query_uris: Optional[OneOrMany[URI]] = ..., ids: Optional[OneOrMany[ID]] = ..., n_results: int = ..., where: Optional[Where] = ..., where_document: Optional[WhereDocument] = ..., include: Include = ...) -> QueryResult:
        """Get the n_results nearest neighbor embeddings for provided query_embeddings or query_texts.

        Args:
            query_embeddings: The embeddings to get the closes neighbors of. Optional.
            query_texts: The document texts to get the closes neighbors of. Optional.
            query_images: The images to get the closes neighbors of. Optional.
            ids: A subset of ids to search within. Optional.
            n_results: The number of neighbors to return for each query_embedding or query_texts. Optional.
            where: A Where type dict used to filter results by. E.g. `{"$and": [{"color" : "red"}, {"price": {"$gte": 4.20}}]}`. Optional.
            where_document: A WhereDocument type dict used to filter by the documents. E.g. `{"$contains": "hello"}`. Optional.
            include: A list of what to include in the results. Can contain `"embeddings"`, `"metadatas"`, `"documents"`, `"distances"`. Ids are always included. Defaults to `["metadatas", "documents", "distances"]`. Optional.

        Returns:
            QueryResult: A QueryResult object containing the results.

        Raises:
            ValueError: If you don't provide either query_embeddings, query_texts, or query_images
            ValueError: If you provide both query_embeddings and query_texts
            ValueError: If you provide both query_embeddings and query_images
            ValueError: If you provide both query_texts and query_images

        """
        ...
    
    async def modify(self, name: Optional[str] = ..., metadata: Optional[CollectionMetadata] = ..., configuration: Optional[UpdateCollectionConfiguration] = ...) -> None:
        """Modify the collection name or metadata

        Args:
            name: The updated name for the collection. Optional.
            metadata: The updated metadata for the collection. Optional.

        Returns:
            None
        """
        ...
    
    async def fork(self, new_name: str) -> AsyncCollection:
        """Fork the current collection under a new name. The returning collection should contain identical data to the current collection.
        This is an experimental API that only works for Hosted Chroma for now.

        Args:
            new_name: The name of the new collection.

        Returns:
            Collection: A new collection with the specified name and containing identical data to the current collection.
        """
        ...
    
    async def update(self, ids: OneOrMany[ID], embeddings: Optional[Union[OneOrMany[Embedding], OneOrMany[PyEmbedding],]] = ..., metadatas: Optional[OneOrMany[Metadata]] = ..., documents: Optional[OneOrMany[Document]] = ..., images: Optional[OneOrMany[Image]] = ..., uris: Optional[OneOrMany[URI]] = ...) -> None:
        """Update the embeddings, metadatas or documents for provided ids.

        Args:
            ids: The ids of the embeddings to update
            embeddings: The embeddings to update. If None, embeddings will be computed based on the documents or images using the embedding_function set for the Collection. Optional.
            metadatas:  The metadata to associate with the embeddings. When querying, you can filter on this metadata. Optional.
            documents: The documents to associate with the embeddings. Optional.
            images: The images to associate with the embeddings. Optional.
        Returns:
            None
        """
        ...
    
    async def upsert(self, ids: OneOrMany[ID], embeddings: Optional[Union[OneOrMany[Embedding], OneOrMany[PyEmbedding],]] = ..., metadatas: Optional[OneOrMany[Metadata]] = ..., documents: Optional[OneOrMany[Document]] = ..., images: Optional[OneOrMany[Image]] = ..., uris: Optional[OneOrMany[URI]] = ...) -> None:
        """Update the embeddings, metadatas or documents for provided ids, or create them if they don't exist.

        Args:
            ids: The ids of the embeddings to update
            embeddings: The embeddings to add. If None, embeddings will be computed based on the documents using the embedding_function set for the Collection. Optional.
            metadatas:  The metadata to associate with the embeddings. When querying, you can filter on this metadata. Optional.
            documents: The documents to associate with the embeddings. Optional.

        Returns:
            None
        """
        ...
    
    async def delete(self, ids: Optional[IDs] = ..., where: Optional[Where] = ..., where_document: Optional[WhereDocument] = ...) -> None:
        """Delete the embeddings based on ids and/or a where filter

        Args:
            ids: The ids of the embeddings to delete
            where: A Where type dict used to filter the delection by. E.g. `{"$and": [{"color" : "red"}, {"price": {"$gte": 4.20}}]}`. Optional.
            where_document: A WhereDocument type dict used to filter the deletion by the document content. E.g. `{"$contains": "hello"}`. Optional.

        Returns:
            None

        Raises:
            ValueError: If you don't provide either ids, where, or where_document
        """
        ...
    


