"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from queue import Queue
from typing import TYPE_CHECKING, Any

from ray.data.iterator import DataIterator
from ray.train import Checkpoint
from ray.train._internal import session
from ray.train.v2._internal.execution.callback import TrainContextCallback
from ray.train.v2._internal.execution.checkpoint.sync_actor import SynchronizationActor
from ray.train.v2._internal.execution.storage import StorageContext
from ray.train.v2._internal.execution.worker_group.thread_runner import ThreadRunner
from ray.train.v2._internal.util import _copy_doc
from ray.train.v2.api.config import RunConfig

if TYPE_CHECKING: ...
logger = ...

@dataclass
class TrainRunContext:
    """Holds the metadata and context for the current training run."""

    run_id: str = ...
    run_config: RunConfig
    def get_run_config(self) -> RunConfig:
        """Returns the run config of the current training run."""
        ...

@dataclass(frozen=True)
class DistributedContext:
    world_rank: int
    world_size: int
    local_rank: int
    local_world_size: int
    node_rank: int
    ...

@dataclass(frozen=True)
class ExecutionContext:
    """Holds the execution context for the current worker process.

    Every worker process has a single execution context accessed via the
    `TrainContext`, which includes the training thread that is actually
    running the user code.
    """

    synchronization_actor: SynchronizationActor
    result_queue: Queue
    training_thread_runner: ThreadRunner
    train_context_callbacks: list[TrainContextCallback]
    ...

@dataclass
class TrainContext(TrainRunContext):
    distributed_context: DistributedContext
    execution_context: ExecutionContext
    storage_context: StorageContext
    dataset_shards: dict[str, DataIterator]
    checkpoint: Checkpoint | None = ...
    @_copy_doc(session.get_experiment_name)
    def get_experiment_name(self) -> str: ...
    @_copy_doc(session.get_world_size)
    def get_world_size(self) -> int: ...
    @_copy_doc(session.get_world_rank)
    def get_world_rank(self) -> int: ...
    @_copy_doc(session.get_local_rank)
    def get_local_rank(self) -> int: ...
    @_copy_doc(session.get_local_world_size)
    def get_local_world_size(self) -> int: ...
    @_copy_doc(session.get_node_rank)
    def get_node_rank(self) -> int: ...
    @_copy_doc(session.get_storage)
    def get_storage(self):  # -> StorageContext:
        ...
    def get_result_queue(self):  # -> Queue[Any]:
        ...
    def get_synchronization_actor(self): ...
    def get_checkpoint(self):  # -> Checkpoint | None:
        ...
    def get_dataset_shard(self, dataset_name: str) -> DataIterator:
        """Returns the :class:`ray.data.DataIterator` shard for this worker.

        Call :meth:`~ray.data.DataIterator.iter_torch_batches` or
        :meth:`~ray.data.DataIterator.to_tf` on this shard to convert it to the
        appropriate framework-specific data type.

        Args:
            dataset_name: Name of the dataset shard.
        Returns:
            The ``DataIterator`` shard with the given name for this worker.
        Raises:
            KeyError: If the dataset shard with the given name is not found.
        """
        ...

    def get_context_callbacks(self) -> list[TrainContextCallback]: ...
    def report(
        self,
        metrics: dict[str, Any],
        checkpoint: Checkpoint | None = ...,
        checkpoint_dir_name: str | None = ...,
    ):  # -> None:
        """
        Upload checkpoint to remote storage and put a training
        result on the result queue of this worker process.

        Args:
            metrics: The metrics to report.
            checkpoint: The checkpoint to report.
            checkpoint_dir_name: The name of the checkpoint dir
                in this iteration. Note: If not set, the checkpoint will
                be stored in the default storage path. If set, make sure
                this value is unique for each iteration.

        TODO: the report function should be implemented in the worker instead
        of in the train context. The train context should only keep the train
        related information and not the worker related actions. This refactor
        would also require the `TrainContextCallback` to be updated as well.
        """
        ...

_train_context: TrainContext | None = ...
_context_lock = ...

def get_train_context() -> TrainContext: ...
def set_train_context(context) -> None: ...
