"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from functools import partial
from typing import Callable, Optional, Tuple
from ...cache_utils import Cache, DynamicCache
from ...modeling_flash_attention_utils import FlashAttentionKwargs
from ...modeling_outputs import BaseModelOutputWithPast
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS
from ...processing_utils import Unpack
from ...utils import logging
from ..clip.modeling_clip import CLIPMLP
from ..llama.modeling_llama import LlamaAttention, LlamaForCausalLM, LlamaForSequenceClassification, LlamaForTokenClassification, LlamaModel, LlamaPreTrainedModel, LlamaRotaryEmbedding, apply_rotary_pos_emb, eager_attention_forward
from .configuration_phi import PhiConfig

logger = ...
_CHECKPOINT_FOR_DOC = ...
_CONFIG_FOR_DOC = ...
class PhiAttention(LlamaAttention):
    def __init__(self, config: PhiConfig, layer_idx: int) -> None:
        ...
    
    def forward(self, hidden_states: torch.Tensor, position_embeddings: Tuple[torch.Tensor, torch.Tensor], attention_mask: Optional[torch.Tensor], past_key_value: Optional[Cache] = ..., cache_position: Optional[torch.LongTensor] = ..., **kwargs) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:
        ...
    


class PhiMLP(CLIPMLP):
    ...


class PhiDecoderLayer(nn.Module):
    def __init__(self, config: PhiConfig, layer_idx: int) -> None:
        ...
    
    def forward(self, hidden_states: torch.Tensor, attention_mask: Optional[torch.Tensor] = ..., position_ids: Optional[torch.LongTensor] = ..., past_key_value: Optional[Tuple[torch.Tensor]] = ..., output_attentions: Optional[bool] = ..., use_cache: Optional[bool] = ..., cache_position: Optional[torch.LongTensor] = ..., position_embeddings: Optional[Tuple[torch.Tensor, torch.Tensor]] = ..., **kwargs) -> Tuple[torch.FloatTensor, Optional[Tuple[torch.FloatTensor, torch.FloatTensor]]]:
        ...
    


class PhiRotaryEmbedding(LlamaRotaryEmbedding):
    ...


class PhiPreTrainedModel(LlamaPreTrainedModel):
    ...


class PhiModel(LlamaModel):
    def __init__(self, config: PhiConfig) -> None:
        ...
    
    def forward(self, input_ids: Optional[torch.LongTensor] = ..., attention_mask: Optional[torch.Tensor] = ..., position_ids: Optional[torch.LongTensor] = ..., past_key_values: Optional[Cache] = ..., inputs_embeds: Optional[torch.FloatTensor] = ..., use_cache: Optional[bool] = ..., output_attentions: Optional[bool] = ..., output_hidden_states: Optional[bool] = ..., cache_position: Optional[torch.LongTensor] = ..., **flash_attn_kwargs: Unpack[FlashAttentionKwargs]) -> BaseModelOutputWithPast:
        ...
    


class PhiForCausalLM(LlamaForCausalLM):
    def __init__(self, config) -> None:
        ...
    


class PhiForSequenceClassification(LlamaForSequenceClassification):
    ...


class PhiForTokenClassification(LlamaForTokenClassification):
    ...


__all__ = ["PhiPreTrainedModel", "PhiModel", "PhiForCausalLM", "PhiForSequenceClassification", "PhiForTokenClassification"]
