"""
This type stub file was generated by pyright.
"""

import asyncio
import uuid
import numpy as np
import llama_index.core.instrumentation as instrument
from abc import abstractmethod
from enum import Enum
from typing import Any, Callable, Coroutine, List, Optional, Sequence, Tuple
from typing_extensions import Self
from llama_index.core.bridge.pydantic import ConfigDict, Field, model_validator
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.callbacks.schema import CBEventType, EventPayload
from llama_index.core.constants import DEFAULT_EMBED_BATCH_SIZE
from llama_index.core.instrumentation import DispatcherSpanMixin
from llama_index.core.schema import BaseNode, MetadataMode, TransformComponent
from llama_index.core.utils import get_tqdm_iterable
from llama_index.core.async_utils import run_jobs
from llama_index.core.instrumentation.events.embedding import EmbeddingEndEvent, EmbeddingStartEvent

"""Base embeddings file."""
Embedding = List[float]
dispatcher = ...
class SimilarityMode(str, Enum):
    """Modes for similarity/distance."""
    DEFAULT = ...
    DOT_PRODUCT = ...
    EUCLIDEAN = ...


def mean_agg(embeddings: List[Embedding]) -> Embedding:
    """Mean aggregation for embeddings."""
    ...

def similarity(embedding1: Embedding, embedding2: Embedding, mode: SimilarityMode = ...) -> float:
    """Get embedding similarity."""
    ...

class BaseEmbedding(TransformComponent, DispatcherSpanMixin):
    """Base class for embeddings."""
    model_config = ...
    model_name: str = ...
    embed_batch_size: int = ...
    callback_manager: CallbackManager = ...
    num_workers: Optional[int] = ...
    embeddings_cache: Optional[Any] = ...
    @model_validator(mode="after")
    def check_base_embeddings_class(self) -> Self:
        ...
    
    @dispatcher.span
    def get_query_embedding(self, query: str) -> Embedding:
        """
        Embed the input query.

        When embedding a query, depending on the model, a special instruction
        can be prepended to the raw query string. For example, "Represent the
        question for retrieving supporting documents: ". If you're curious,
        other examples of predefined instructions can be found in
        embeddings/huggingface_utils.py.
        """
        ...
    
    @dispatcher.span
    async def aget_query_embedding(self, query: str) -> Embedding:
        """Get query embedding."""
        ...
    
    def get_agg_embedding_from_queries(self, queries: List[str], agg_fn: Optional[Callable[..., Embedding]] = ...) -> Embedding:
        """Get aggregated embedding from multiple queries."""
        ...
    
    async def aget_agg_embedding_from_queries(self, queries: List[str], agg_fn: Optional[Callable[..., Embedding]] = ...) -> Embedding:
        """Async get aggregated embedding from multiple queries."""
        ...
    
    @dispatcher.span
    def get_text_embedding(self, text: str) -> Embedding:
        """
        Embed the input text.

        When embedding text, depending on the model, a special instruction
        can be prepended to the raw text string. For example, "Represent the
        document for retrieval: ". If you're curious, other examples of
        predefined instructions can be found in embeddings/huggingface_utils.py.
        """
        ...
    
    @dispatcher.span
    async def aget_text_embedding(self, text: str) -> Embedding:
        """Async get text embedding."""
        ...
    
    @dispatcher.span
    def get_text_embedding_batch(self, texts: List[str], show_progress: bool = ..., **kwargs: Any) -> List[Embedding]:
        """Get a list of text embeddings, with batching."""
        ...
    
    @dispatcher.span
    async def aget_text_embedding_batch(self, texts: List[str], show_progress: bool = ...) -> List[Embedding]:
        """Asynchronously get a list of text embeddings, with batching."""
        ...
    
    def similarity(self, embedding1: Embedding, embedding2: Embedding, mode: SimilarityMode = ...) -> float:
        """Get embedding similarity."""
        ...
    
    def __call__(self, nodes: Sequence[BaseNode], **kwargs: Any) -> Sequence[BaseNode]:
        ...
    
    async def acall(self, nodes: Sequence[BaseNode], **kwargs: Any) -> Sequence[BaseNode]:
        ...
    


