"""
This type stub file was generated by pyright.
"""

import types
from contextlib import contextmanager
from torch.backends import cpu as cpu, cuda as cuda, cudnn as cudnn, cusparselt as cusparselt, kleidiai as kleidiai, mha as mha, mkl as mkl, mkldnn as mkldnn, mps as mps, nnpack as nnpack, openmp as openmp, quantized as quantized

__allow_nonbracketed_mutation_flag = ...
def disable_global_flags(): # -> None:
    ...

def flags_frozen(): # -> bool:
    ...

class ContextProp:
    def __init__(self, getter, setter) -> None:
        ...
    
    def __get__(self, obj, objtype):
        ...
    
    def __set__(self, obj, val): # -> None:
        ...
    


class PropModule(types.ModuleType):
    def __init__(self, m, name) -> None:
        ...
    
    def __getattr__(self, attr):
        ...
    


