"""
This type stub file was generated by pyright.
"""

from typing import Any

from compressed_tensors.quantization.quant_args import QuantizationArgs
from pydantic import BaseModel, model_validator

__all__ = ["QuantizationScheme", "preset_name_to_scheme", "is_preset_scheme"]

class QuantizationScheme(BaseModel):
    """
    Set of QuantizationArgs defining how the weights, inputs and outputs of target list
    of modules should be quantized

    :param targets: list of modules to apply the QuantizationArgs to, can be layer
    names, layer types or a regular expression, typically ["Linear"]
    :param weights: quantization config for layer weights
    :param input_activations: quantization config for layer inputs
    :param output_activations: quantization config for layer outputs
    """

    targets: list[str]
    weights: QuantizationArgs | None = ...
    input_activations: QuantizationArgs | None = ...
    output_activations: QuantizationArgs | None = ...
    @model_validator(mode="after")
    def validate_model_after(model: QuantizationArgs) -> dict[str, Any]: ...

def preset_name_to_scheme(name: str, targets: list[str]) -> QuantizationScheme:
    """
    :param name: preset quantization settings name. must exist in upper case in
        PRESET_SCHEMES
    :param targets: list of quantization targets to be passed to the Scheme
    :return: new QuantizationScheme for a given name with the given targets
    """
    ...

def is_preset_scheme(name: str) -> bool:
    """
    :param name: preset quantization settings name
    :return: True if the name is a preset scheme name
    """
    ...

UNQUANTIZED = ...
INT8_W8A8 = ...
W8A16 = ...
W4A16 = ...
W4A16_ASYM = ...
INT8_W4A8 = ...
FP8 = ...
FP8_DYNAMIC = ...
PRESET_SCHEMES = ...
