"""
This type stub file was generated by pyright.
"""

import inspect
from typing import TYPE_CHECKING, Any

from llama_index_instrumentation.span.simple import SimpleSpan

from .base import BaseSpanHandler

if TYPE_CHECKING: ...

class SimpleSpanHandler(BaseSpanHandler[SimpleSpan]):
    """Span Handler that manages SimpleSpan's."""
    def class_name(cls) -> str:
        """Class name."""
        ...

    def new_span(
        self,
        id_: str,
        bound_args: inspect.BoundArguments,
        instance: Any | None = ...,
        parent_span_id: str | None = ...,
        tags: dict[str, Any] | None = ...,
        **kwargs: Any,
    ) -> SimpleSpan:
        """Create a span."""
        ...

    def prepare_to_exit_span(
        self,
        id_: str,
        bound_args: inspect.BoundArguments,
        instance: Any | None = ...,
        result: Any | None = ...,
        **kwargs: Any,
    ) -> SimpleSpan:
        """Logic for preparing to drop a span."""
        ...

    def prepare_to_drop_span(
        self,
        id_: str,
        bound_args: inspect.BoundArguments,
        instance: Any | None = ...,
        err: BaseException | None = ...,
        **kwargs: Any,
    ) -> SimpleSpan | None:
        """Logic for droppping a span."""
        ...

    def print_trace_trees(self) -> None:
        """Method for viewing trace trees."""
        ...
