"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any

import ray.util.client_connect
from ray._private.worker import BaseContext
from ray.util.annotations import Deprecated, PublicAPI

logger = ...
CLIENT_DOCS_URL = ...

@dataclass
@PublicAPI
class ClientContext(BaseContext):
    """
    Basic context manager for a ClientBuilder connection.

    `protocol_version` is no longer used.
    """

    dashboard_url: str | None
    python_version: str
    ray_version: str
    ray_commit: str
    _num_clients: int
    _context_to_restore: ray.util.client.RayAPIStub | None
    protocol_version: str | None = ...
    def __enter__(self) -> ClientContext: ...
    def __exit__(self, *exc) -> None: ...
    def disconnect(self) -> None: ...

@Deprecated
class ClientBuilder:
    """
    Builder for a Ray Client connection. This class can be subclassed by
    custom builder classes to modify connection behavior to include additional
    features or altered semantics. One example is the ``_LocalClientBuilder``.
    """
    def __init__(self, address: str | None) -> None: ...
    def env(self, env: dict[str, Any]) -> ClientBuilder:
        """
        Set an environment for the session.
        Args:
            env (Dict[st, Any]): A runtime environment to use for this
            connection. See :ref:`runtime-environments` for what values are
            accepted in this dict.
        """
        ...

    def namespace(self, namespace: str) -> ClientBuilder:
        """
        Sets the namespace for the session.
        Args:
            namespace: Namespace to use.
        """
        ...

    def connect(self) -> ClientContext:
        """
        Begin a connection to the address passed in via ray.client(...).

        Returns:
            ClientInfo: Dataclass with information about the setting. This
                includes the server's version of Python & Ray as well as the
                dashboard_url.
        """
        ...

class _LocalClientBuilder(ClientBuilder):
    def connect(self) -> ClientContext:
        """
        Begin a connection to the address passed in via ray.client(...)
        """
        ...

@Deprecated
def client(address: str | None = ..., _deprecation_warn_enabled: bool = ...) -> ClientBuilder:
    """
    Creates a ClientBuilder based on the provided address. The address can be
    of the following forms:

        * None: Connects to or creates a local cluster and connects to it.
        * ``"local"``: Creates a new cluster locally and connects to it.
        * ``"IP:Port"``: Connects to a Ray Client Server at the given address.
        * ``"module://inner_address"``: load module.ClientBuilder & pass
            inner_address

    The _deprecation_warn_enabled flag enables deprecation warnings, and is
    for internal use only. Set it to False to suppress client deprecation
    warnings.
    """
    ...
