"""
This type stub file was generated by pyright.
"""

from typing import Protocol, runtime_checkable

from llama_index.core.schema import BaseNode, TextNode

"""General node utils."""
logger = ...

@runtime_checkable
class IdFuncCallable(Protocol):
    def __call__(self, i: int, doc: BaseNode) -> str: ...

def default_id_func(i: int, doc: BaseNode) -> str: ...
def build_nodes_from_splits(
    text_splits: list[str],
    document: BaseNode,
    ref_doc: BaseNode | None = ...,
    id_func: IdFuncCallable | None = ...,
) -> list[TextNode]:
    """Build nodes from splits."""
    ...
