"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any

from llama_index.core.base.llms.types import ChatMessage

class TokenCounter:
    """
    Token counter class.

    Attributes:
        model (Optional[str]): The model to use for token counting.

    """
    def __init__(self, tokenizer: Callable[[str], list] | None = ...) -> None: ...
    def get_string_tokens(self, string: str) -> int:
        """
        Get the token count for a string.

        Args:
            string (str): The string to count.

        Returns:
            int: The token count.

        """
        ...

    def estimate_tokens_in_messages(self, messages: list[ChatMessage]) -> int:
        """
        Estimate token count for a single message.

        Args:
            message (OpenAIMessage): The message to estimate the token count for.

        Returns:
            int: The estimated token count.

        """
        ...

    def estimate_tokens_in_tools(self, tools: list[dict[str, Any]]) -> int:
        """
        Estimate token count for the tools.

        We take here a list of tools created using the `to_openai_tool()` function (or similar).

        Args:
            tools (list[Dict[str, Any]]): The tools to estimate the token count for.

        Returns:
            int: The estimated token count.

        """
        ...
