"""
This type stub file was generated by pyright.
"""

import numpy as np
import torch
from copy import deepcopy
from typing import List, Optional, Union
from ...image_utils import ImageInput
from ...processing_utils import ImagesKwargs, ProcessingKwargs, ProcessorMixin, Unpack
from ...tokenization_utils_base import AudioInput, BatchEncoding, PreTokenizedInput, TextInput
from ...utils import is_torch_available
from ...video_utils import VideoInput

"""
Processor class for SAMHQ.
"""
if is_torch_available():
    ...
class SamHQImagesKwargs(ImagesKwargs):
    segmentation_maps: Optional[ImageInput]
    input_points: Optional[List[List[float]]]
    input_labels: Optional[List[List[int]]]
    input_boxes: Optional[List[List[List[float]]]]
    point_pad_value: Optional[int]
    ...


class SamHQProcessorKwargs(ProcessingKwargs, total=False):
    images_kwargs: SamHQImagesKwargs
    _defaults = ...


class SamHQProcessor(ProcessorMixin):
    r"""
    Constructs a SAM HQ processor which wraps a SAM  image processor and an 2D points & Bounding boxes processor into a
    single processor.

    [`SamHQProcessor`] offers all the functionalities of [`SamImageProcessor`]. See the docstring of
    [`~SamImageProcessor.__call__`] for more information.

    Args:
        image_processor (`SamImageProcessor`):
            An instance of [`SamImageProcessor`]. The image processor is a required input.
    """
    attributes = ...
    image_processor_class = ...
    optional_call_args = ...
    def __init__(self, image_processor) -> None:
        ...
    
    def __call__(self, images: Optional[ImageInput] = ..., *args, text: Optional[Union[TextInput, PreTokenizedInput, List[TextInput], List[PreTokenizedInput]]] = ..., audio: Optional[AudioInput] = ..., video: Optional[VideoInput] = ..., **kwargs: Unpack[SamHQProcessorKwargs]) -> BatchEncoding:
        """
        This method uses [`SamImageProcessor.__call__`] method to prepare image(s) for the model. It also prepares 2D
        points and bounding boxes for the model if they are provided.
        """
        ...
    
    @property
    def model_input_names(self): # -> list[Any]:
        ...
    
    def post_process_masks(self, *args, **kwargs):
        ...
    


__all__ = ["SamHQProcessor"]
