"""
This type stub file was generated by pyright.
"""

import torch
from typing import List, Union
from ...feature_extraction_utils import BatchFeature
from ...processing_utils import ProcessorMixin
from ...tokenization_utils import PreTokenizedInput, TextInput
from ...utils import is_torch_available, logging
from ...utils.import_utils import requires_backends

"""Processor class for Granite Speech."""
if is_torch_available():
    ...
logger = ...
class GraniteSpeechProcessor(ProcessorMixin):
    attributes = ...
    valid_kwargs = ...
    audio_processor_class = ...
    tokenizer_class = ...
    def __init__(self, audio_processor, tokenizer, audio_token=..., chat_template=...) -> None:
        ...
    
    def __call__(self, text: Union[TextInput, PreTokenizedInput, List[TextInput], List[PreTokenizedInput]], audio: Union[torch.Tensor, List[torch.Tensor]] = ..., device: str = ..., images=..., videos=..., **kwargs) -> BatchFeature:
        ...
    


__all__ = ["GraniteSpeechProcessor"]
