"""
This type stub file was generated by pyright.
"""

from llama_index_instrumentation import DispatcherSpanMixin, get_dispatcher, root_dispatcher, root_manager
from llama_index_instrumentation.dispatcher import DISPATCHER_SPAN_DECORATED_ATTR, Dispatcher, Manager
from llama_index_instrumentation.event_handlers import NullEventHandler
from llama_index_instrumentation.span_handlers import NullSpanHandler

