"""
This type stub file was generated by pyright.
"""

import llama_index.core.instrumentation as instrument
from abc import abstractmethod
from typing import Any, Dict, List, Optional
from llama_index.core.base.base_query_engine import BaseQueryEngine
from llama_index.core.base.query_pipeline.query import ChainableMixin, InputKeys, OutputKeys, QueryComponent, validate_and_convert_stringable
from llama_index.core.bridge.pydantic import ConfigDict, Field
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.callbacks.schema import CBEventType, EventPayload
from llama_index.core.prompts.mixin import PromptDictType, PromptMixin, PromptMixinType
from llama_index.core.schema import BaseNode, IndexNode, NodeWithScore, QueryBundle, QueryType, TextNode
from llama_index.core.settings import Settings
from llama_index.core.utils import print_text
from llama_index.core.instrumentation import DispatcherSpanMixin
from llama_index.core.instrumentation.events.retrieval import RetrievalEndEvent, RetrievalStartEvent

"""Base retriever."""
dispatcher = ...
class BaseRetriever(ChainableMixin, PromptMixin, DispatcherSpanMixin):
    """Base retriever."""
    def __init__(self, callback_manager: Optional[CallbackManager] = ..., object_map: Optional[Dict] = ..., objects: Optional[List[IndexNode]] = ..., verbose: bool = ...) -> None:
        ...
    
    @dispatcher.span
    def retrieve(self, str_or_query_bundle: QueryType) -> List[NodeWithScore]:
        """
        Retrieve nodes given query.

        Args:
            str_or_query_bundle (QueryType): Either a query string or
                a QueryBundle object.

        """
        ...
    
    @dispatcher.span
    async def aretrieve(self, str_or_query_bundle: QueryType) -> List[NodeWithScore]:
        ...
    


class RetrieverComponent(QueryComponent):
    """Retriever component."""
    model_config = ...
    retriever: BaseRetriever = ...
    def set_callback_manager(self, callback_manager: CallbackManager) -> None:
        """Set callback manager."""
        ...
    
    @property
    def input_keys(self) -> InputKeys:
        """Input keys."""
        ...
    
    @property
    def output_keys(self) -> OutputKeys:
        """Output keys."""
        ...
    


