"""
This type stub file was generated by pyright.
"""

import sys
from pathlib import Path
from typing import TYPE_CHECKING, Literal

from platformdirs.unix import Unix as _Result

from .api import PlatformDirsABC
from .version import __version__
from .version import __version_tuple__ as __version_info__

"""
Utilities for determining application-specific dirs.

See <https://github.com/platformdirs/platformdirs> for details and usage.

"""
if TYPE_CHECKING: ...
if sys.platform == "win32": ...
else: ...
if TYPE_CHECKING:
    PlatformDirs = _Result
else: ...
AppDirs = PlatformDirs

def user_data_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    roaming: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: data directory tied to the user
    """
    ...

def site_data_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    multipath: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param multipath: See `roaming <platformdirs.api.PlatformDirsABC.multipath>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: data directory shared by users
    """
    ...

def user_config_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    roaming: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: config directory tied to the user
    """
    ...

def site_config_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    multipath: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param multipath: See `roaming <platformdirs.api.PlatformDirsABC.multipath>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: config directory shared by the users
    """
    ...

def user_cache_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: cache directory tied to the user
    """
    ...

def site_cache_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: cache directory tied to the user
    """
    ...

def user_state_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    roaming: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: state directory tied to the user
    """
    ...

def user_log_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: log directory tied to the user
    """
    ...

def user_documents_dir() -> str:
    """:returns: documents directory tied to the user"""
    ...

def user_downloads_dir() -> str:
    """:returns: downloads directory tied to the user"""
    ...

def user_pictures_dir() -> str:
    """:returns: pictures directory tied to the user"""
    ...

def user_videos_dir() -> str:
    """:returns: videos directory tied to the user"""
    ...

def user_music_dir() -> str:
    """:returns: music directory tied to the user"""
    ...

def user_desktop_dir() -> str:
    """:returns: desktop directory tied to the user"""
    ...

def user_runtime_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: runtime directory tied to the user
    """
    ...

def site_runtime_dir(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> str:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: runtime directory shared by users
    """
    ...

def user_data_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    roaming: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: data path tied to the user
    """
    ...

def site_data_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    multipath: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param multipath: See `multipath <platformdirs.api.PlatformDirsABC.multipath>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: data path shared by users
    """
    ...

def user_config_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    roaming: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: config path tied to the user
    """
    ...

def site_config_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    multipath: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param multipath: See `roaming <platformdirs.api.PlatformDirsABC.multipath>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: config path shared by the users
    """
    ...

def site_cache_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: cache directory tied to the user
    """
    ...

def user_cache_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: cache path tied to the user
    """
    ...

def user_state_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    roaming: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param roaming: See `roaming <platformdirs.api.PlatformDirsABC.roaming>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: state path tied to the user
    """
    ...

def user_log_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `roaming <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: log path tied to the user
    """
    ...

def user_documents_path() -> Path:
    """:returns: documents a path tied to the user"""
    ...

def user_downloads_path() -> Path:
    """:returns: downloads path tied to the user"""
    ...

def user_pictures_path() -> Path:
    """:returns: pictures path tied to the user"""
    ...

def user_videos_path() -> Path:
    """:returns: videos path tied to the user"""
    ...

def user_music_path() -> Path:
    """:returns: music path tied to the user"""
    ...

def user_desktop_path() -> Path:
    """:returns: desktop path tied to the user"""
    ...

def user_runtime_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: runtime path tied to the user
    """
    ...

def site_runtime_path(
    appname: str | None = ...,
    appauthor: str | Literal[False] | None = ...,
    version: str | None = ...,
    opinion: bool = ...,
    ensure_exists: bool = ...,
) -> Path:
    """
    :param appname: See `appname <platformdirs.api.PlatformDirsABC.appname>`.
    :param appauthor: See `appauthor <platformdirs.api.PlatformDirsABC.appauthor>`.
    :param version: See `version <platformdirs.api.PlatformDirsABC.version>`.
    :param opinion: See `opinion <platformdirs.api.PlatformDirsABC.opinion>`.
    :param ensure_exists: See `ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
    :returns: runtime path shared by users
    """
    ...

__all__ = [
    "AppDirs",
    "PlatformDirs",
    "PlatformDirsABC",
    "__version__",
    "__version_info__",
    "site_cache_dir",
    "site_cache_path",
    "site_config_dir",
    "site_config_path",
    "site_data_dir",
    "site_data_path",
    "site_runtime_dir",
    "site_runtime_path",
    "user_cache_dir",
    "user_cache_path",
    "user_config_dir",
    "user_config_path",
    "user_data_dir",
    "user_data_path",
    "user_desktop_dir",
    "user_desktop_path",
    "user_documents_dir",
    "user_documents_path",
    "user_downloads_dir",
    "user_downloads_path",
    "user_log_dir",
    "user_log_path",
    "user_music_dir",
    "user_music_path",
    "user_pictures_dir",
    "user_pictures_path",
    "user_runtime_dir",
    "user_runtime_path",
    "user_state_dir",
    "user_state_path",
    "user_videos_dir",
    "user_videos_path",
]
