"""
This type stub file was generated by pyright.
"""

import contextlib
import json
import re
from typing import Any, List
from llama_index.core.output_parsers.base import OutputParserException

def parse_json_markdown(text: str) -> Any:
    ...

def parse_code_markdown(text: str, only_last: bool) -> List[str]:
    ...

def extract_json_str(text: str) -> str:
    """Extract JSON string from text."""
    ...

