"""
This type stub file was generated by pyright.
"""

from typing import Any

def parse_json_markdown(text: str) -> Any: ...
def parse_code_markdown(text: str, only_last: bool) -> list[str]: ...
def extract_json_str(text: str) -> str:
    """Extract JSON string from text."""
    ...
