"""
This type stub file was generated by pyright.
"""

import torch
from torch import absolute as fabs, arccos, arccosh, arcsin, arcsinh, arctan, arctanh, bitwise_not, ceil, conj_physical as conjugate, cos, cosh, deg2rad, exp, exp2, expm1, floor, isfinite, isinf, isnan, log, log10, log1p, log2, logical_not, negative, rad2deg, reciprocal, round as fix, sign, signbit, sin, sinh, sqrt, square, tan, tanh, trunc

"""Export torch work functions for unary ufuncs, rename/tweak to match numpy.
This listing is further exported to public symbols in the `_numpy/_ufuncs.py` module.
"""
def cbrt(x): # -> Tensor:
    ...

def positive(x):
    ...

def absolute(x): # -> Tensor:
    ...

abs = ...
conj = ...
