"""
This type stub file was generated by pyright.
"""

import logging
import os
from typing import Optional
from torch._inductor import config
from torch._inductor.utils import is_linux

log = ...
def rocm_compiler() -> Optional[str]:
    ...

def rocm_compile_command(src_files: list[str], dst_file: str, dst_file_ext: str, extra_args: Optional[list[str]] = ...) -> str:
    ...

