"""
This type stub file was generated by pyright.
"""

from collections.abc import Awaitable, Callable
from typing import Any

from llama_index.core.bridge.pydantic import BaseModel

def create_schema_from_function(
    name: str,
    func: Callable[..., Any] | Callable[..., Awaitable[Any]],
    additional_fields: list[tuple[str, type, Any] | tuple[str, type]] | None = ...,
    ignore_fields: list[str] | None = ...,
) -> type[BaseModel]:
    """Create schema from function."""
    ...
