"""
This type stub file was generated by pyright.
"""

import typing
from inspect import signature
from typing import Any, Awaitable, Callable, List, Optional, Tuple, Type, Union, cast, get_args, get_origin
from llama_index.core.bridge.pydantic import BaseModel, FieldInfo, create_model

def create_schema_from_function(name: str, func: Union[Callable[..., Any], Callable[..., Awaitable[Any]]], additional_fields: Optional[List[Union[Tuple[str, Type, Any], Tuple[str, Type]]]] = ..., ignore_fields: Optional[List[str]] = ...) -> Type[BaseModel]:
    """Create schema from function."""
    ...

