"""
This type stub file was generated by pyright.
"""

import asyncio
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from llama_index.core.base.query_pipeline.query import ChainableMixin, InputKeys, OutputKeys, QueryComponent, validate_and_convert_stringable
from llama_index.core.bridge.pydantic import ConfigDict, Field, SerializeAsAny
from llama_index.core.callbacks import CallbackManager
from llama_index.core.instrumentation import DispatcherSpanMixin
from llama_index.core.prompts.mixin import PromptDictType, PromptMixinType
from llama_index.core.schema import BaseComponent, NodeWithScore, QueryBundle

class BaseNodePostprocessor(ChainableMixin, BaseComponent, DispatcherSpanMixin, ABC):
    model_config = ...
    callback_manager: CallbackManager = ...
    @classmethod
    def class_name(cls) -> str:
        ...
    
    def postprocess_nodes(self, nodes: List[NodeWithScore], query_bundle: Optional[QueryBundle] = ..., query_str: Optional[str] = ...) -> List[NodeWithScore]:
        """Postprocess nodes."""
        ...
    
    async def apostprocess_nodes(self, nodes: List[NodeWithScore], query_bundle: Optional[QueryBundle] = ..., query_str: Optional[str] = ...) -> List[NodeWithScore]:
        """Postprocess nodes (async)."""
        ...
    


class PostprocessorComponent(QueryComponent):
    """Postprocessor component."""
    model_config = ...
    postprocessor: SerializeAsAny[BaseNodePostprocessor] = ...
    def set_callback_manager(self, callback_manager: CallbackManager) -> None:
        """Set callback manager."""
        ...
    
    @property
    def input_keys(self) -> InputKeys:
        """Input keys."""
        ...
    
    @property
    def output_keys(self) -> OutputKeys:
        """Output keys."""
        ...
    


