"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from typing import Any, Union

from deprecated import deprecated
from llama_index.core.base.llms.types import ChatMessage, LogProb
from llama_index.core.bridge.pydantic import BaseModel
from openai.types.chat import ChatCompletionMessageParam, ChatCompletionMessageToolCall
from openai.types.chat.chat_completion_chunk import ChoiceDeltaToolCall
from openai.types.chat.chat_completion_message import ChatCompletionMessage
from openai.types.chat.chat_completion_token_logprob import ChatCompletionTokenLogprob
from openai.types.completion_choice import Logprobs

DEFAULT_OPENAI_API_TYPE = ...
DEFAULT_OPENAI_API_BASE = ...
DEFAULT_OPENAI_API_VERSION = ...
O1_MODELS: dict[str, int] = ...
O1_MODELS_WITHOUT_FUNCTION_CALLING = ...
GPT4_MODELS: dict[str, int] = ...
AZURE_TURBO_MODELS: dict[str, int] = ...
TURBO_MODELS: dict[str, int] = ...
GPT3_5_MODELS: dict[str, int] = ...
GPT3_MODELS: dict[str, int] = ...
ALL_AVAILABLE_MODELS = ...
CHAT_MODELS = ...
DISCONTINUED_MODELS = ...
JSON_SCHEMA_MODELS = ...

def is_json_schema_supported(model: str) -> bool: ...

MISSING_API_KEY_ERROR_MESSAGE = ...
logger = ...
OpenAIToolCall = Union[ChatCompletionMessageToolCall, ChoiceDeltaToolCall]

def create_retry_decorator(
    max_retries: int,
    random_exponential: bool = ...,
    stop_after_delay_seconds: float | None = ...,
    min_seconds: float = ...,
    max_seconds: float = ...,
) -> Callable[[Any], Any]: ...
def openai_modelname_to_contextsize(modelname: str) -> int:
    """
    Calculate the maximum number of tokens possible to generate for a model.

    Args:
        modelname: The modelname we want to know the context size for.

    Returns:
        The maximum context size

    Example:
        .. code-block:: python

            max_tokens = openai.modelname_to_contextsize("text-davinci-003")

    Modified from:
        https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py
    """
    ...

def is_chat_model(model: str) -> bool: ...
def is_function_calling_model(model: str) -> bool: ...
def to_openai_message_dict(
    message: ChatMessage, drop_none: bool = ..., model: str | None = ...
) -> ChatCompletionMessageParam:
    """Convert a ChatMessage to an OpenAI message dict."""
    ...

def to_openai_responses_message_dict(
    message: ChatMessage, drop_none: bool = ..., model: str | None = ...
) -> str | dict[str, Any] | list[dict[str, Any]]:
    """Convert a ChatMessage to an OpenAI message dict."""
    ...

def to_openai_message_dicts(
    messages: Sequence[ChatMessage],
    drop_none: bool = ...,
    model: str | None = ...,
    is_responses_api: bool = ...,
) -> list[ChatCompletionMessageParam] | str:
    """Convert generic messages to OpenAI message dicts."""
    ...

def from_openai_message(
    openai_message: ChatCompletionMessage, modalities: list[str]
) -> ChatMessage:
    """Convert openai message dict to generic message."""
    ...

def from_openai_token_logprob(openai_token_logprob: ChatCompletionTokenLogprob) -> list[LogProb]:
    """Convert a single openai token logprob to generic list of logprobs."""
    ...

def from_openai_token_logprobs(
    openai_token_logprobs: Sequence[ChatCompletionTokenLogprob],
) -> list[list[LogProb]]:
    """Convert openai token logprobs to generic list of LogProb."""
    ...

def from_openai_completion_logprob(openai_completion_logprob: dict[str, float]) -> list[LogProb]:
    """Convert openai completion logprobs to generic list of LogProb."""
    ...

def from_openai_completion_logprobs(openai_completion_logprobs: Logprobs) -> list[list[LogProb]]:
    """Convert openai completion logprobs to generic list of LogProb."""
    ...

def from_openai_messages(
    openai_messages: Sequence[ChatCompletionMessage], modalities: list[str]
) -> list[ChatMessage]:
    """Convert openai message dicts to generic messages."""
    ...

def from_openai_message_dict(message_dict: dict) -> ChatMessage:
    """Convert openai message dict to generic message."""
    ...

def from_openai_message_dicts(message_dicts: Sequence[dict]) -> list[ChatMessage]:
    """Convert openai message dicts to generic messages."""
    ...

@deprecated("Deprecated in favor of `to_openai_tool`, which should be used instead.")
def to_openai_function(pydantic_class: type[BaseModel]) -> dict[str, Any]:
    """
    Deprecated in favor of `to_openai_tool`.

    Convert pydantic class to OpenAI function.
    """
    ...

def to_openai_tool(
    pydantic_class: type[BaseModel], description: str | None = ...
) -> dict[str, Any]:
    """Convert pydantic class to OpenAI tool."""
    ...

def resolve_openai_credentials(
    api_key: str | None = ..., api_base: str | None = ..., api_version: str | None = ...
) -> tuple[str | None, str, str]:
    """
    "Resolve OpenAI credentials.

    The order of precedence is:
    1. param
    2. env
    3. openai module
    4. default
    """
    ...

def validate_openai_api_key(api_key: str | None = ...) -> None: ...
def resolve_tool_choice(tool_choice: str | dict | None, tool_required: bool = ...) -> str | dict:
    """
    Resolve tool choice.

    If tool_choice is a function name string, return the appropriate dict.
    """
    ...

def update_tool_calls(
    tool_calls: list[ChoiceDeltaToolCall], tool_calls_delta: list[ChoiceDeltaToolCall] | None
) -> list[ChoiceDeltaToolCall]:
    """
    Use the tool_calls_delta objects received from openai stream chunks
    to update the running tool_calls object.

    Args:
        tool_calls (List[ChoiceDeltaToolCall]): the list of tool calls
        tool_calls_delta (ChoiceDeltaToolCall): the delta to update tool_calls

    Returns:
        List[ChoiceDeltaToolCall]: the updated tool calls
    """
    ...
