"""
This type stub file was generated by pyright.
"""

import logging
import os
import openai
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Type, Union
from deprecated import deprecated
from openai.types.chat import ChatCompletionMessageParam, ChatCompletionMessageToolCall
from openai.types.chat.chat_completion_chunk import ChoiceDeltaToolCall
from openai.types.chat.chat_completion_message import ChatCompletionMessage
from openai.types.chat.chat_completion_token_logprob import ChatCompletionTokenLogprob
from openai.types.completion_choice import Logprobs
from tenacity import before_sleep_log, retry, retry_if_exception_type, stop_after_attempt, stop_after_delay, wait_exponential, wait_random_exponential
from tenacity.stop import stop_base
from llama_index.core.base.llms.generic_utils import get_from_param_or_env
from llama_index.core.base.llms.types import AudioBlock, ChatMessage, DocumentBlock, ImageBlock, LogProb, MessageRole, TextBlock
from llama_index.core.bridge.pydantic import BaseModel

DEFAULT_OPENAI_API_TYPE = ...
DEFAULT_OPENAI_API_BASE = ...
DEFAULT_OPENAI_API_VERSION = ...
O1_MODELS: Dict[str, int] = ...
O1_MODELS_WITHOUT_FUNCTION_CALLING = ...
GPT4_MODELS: Dict[str, int] = ...
AZURE_TURBO_MODELS: Dict[str, int] = ...
TURBO_MODELS: Dict[str, int] = ...
GPT3_5_MODELS: Dict[str, int] = ...
GPT3_MODELS: Dict[str, int] = ...
ALL_AVAILABLE_MODELS = ...
CHAT_MODELS = ...
DISCONTINUED_MODELS = ...
JSON_SCHEMA_MODELS = ...
def is_json_schema_supported(model: str) -> bool:
    ...

MISSING_API_KEY_ERROR_MESSAGE = ...
logger = ...
OpenAIToolCall = Union[ChatCompletionMessageToolCall, ChoiceDeltaToolCall]
def create_retry_decorator(max_retries: int, random_exponential: bool = ..., stop_after_delay_seconds: Optional[float] = ..., min_seconds: float = ..., max_seconds: float = ...) -> Callable[[Any], Any]:
    ...

def openai_modelname_to_contextsize(modelname: str) -> int:
    """
    Calculate the maximum number of tokens possible to generate for a model.

    Args:
        modelname: The modelname we want to know the context size for.

    Returns:
        The maximum context size

    Example:
        .. code-block:: python

            max_tokens = openai.modelname_to_contextsize("text-davinci-003")

    Modified from:
        https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py
    """
    ...

def is_chat_model(model: str) -> bool:
    ...

def is_function_calling_model(model: str) -> bool:
    ...

def to_openai_message_dict(message: ChatMessage, drop_none: bool = ..., model: Optional[str] = ...) -> ChatCompletionMessageParam:
    """Convert a ChatMessage to an OpenAI message dict."""
    ...

def to_openai_responses_message_dict(message: ChatMessage, drop_none: bool = ..., model: Optional[str] = ...) -> Union[str, Dict[str, Any], List[Dict[str, Any]]]:
    """Convert a ChatMessage to an OpenAI message dict."""
    ...

def to_openai_message_dicts(messages: Sequence[ChatMessage], drop_none: bool = ..., model: Optional[str] = ..., is_responses_api: bool = ...) -> Union[List[ChatCompletionMessageParam], str]:
    """Convert generic messages to OpenAI message dicts."""
    ...

def from_openai_message(openai_message: ChatCompletionMessage, modalities: List[str]) -> ChatMessage:
    """Convert openai message dict to generic message."""
    ...

def from_openai_token_logprob(openai_token_logprob: ChatCompletionTokenLogprob) -> List[LogProb]:
    """Convert a single openai token logprob to generic list of logprobs."""
    ...

def from_openai_token_logprobs(openai_token_logprobs: Sequence[ChatCompletionTokenLogprob]) -> List[List[LogProb]]:
    """Convert openai token logprobs to generic list of LogProb."""
    ...

def from_openai_completion_logprob(openai_completion_logprob: Dict[str, float]) -> List[LogProb]:
    """Convert openai completion logprobs to generic list of LogProb."""
    ...

def from_openai_completion_logprobs(openai_completion_logprobs: Logprobs) -> List[List[LogProb]]:
    """Convert openai completion logprobs to generic list of LogProb."""
    ...

def from_openai_messages(openai_messages: Sequence[ChatCompletionMessage], modalities: List[str]) -> List[ChatMessage]:
    """Convert openai message dicts to generic messages."""
    ...

def from_openai_message_dict(message_dict: dict) -> ChatMessage:
    """Convert openai message dict to generic message."""
    ...

def from_openai_message_dicts(message_dicts: Sequence[dict]) -> List[ChatMessage]:
    """Convert openai message dicts to generic messages."""
    ...

@deprecated("Deprecated in favor of `to_openai_tool`, which should be used instead.")
def to_openai_function(pydantic_class: Type[BaseModel]) -> Dict[str, Any]:
    """
    Deprecated in favor of `to_openai_tool`.

    Convert pydantic class to OpenAI function.
    """
    ...

def to_openai_tool(pydantic_class: Type[BaseModel], description: Optional[str] = ...) -> Dict[str, Any]:
    """Convert pydantic class to OpenAI tool."""
    ...

def resolve_openai_credentials(api_key: Optional[str] = ..., api_base: Optional[str] = ..., api_version: Optional[str] = ...) -> Tuple[Optional[str], str, str]:
    """
    "Resolve OpenAI credentials.

    The order of precedence is:
    1. param
    2. env
    3. openai module
    4. default
    """
    ...

def validate_openai_api_key(api_key: Optional[str] = ...) -> None:
    ...

def resolve_tool_choice(tool_choice: Optional[Union[str, dict]], tool_required: bool = ...) -> Union[str, dict]:
    """
    Resolve tool choice.

    If tool_choice is a function name string, return the appropriate dict.
    """
    ...

def update_tool_calls(tool_calls: List[ChoiceDeltaToolCall], tool_calls_delta: Optional[List[ChoiceDeltaToolCall]]) -> List[ChoiceDeltaToolCall]:
    """
    Use the tool_calls_delta objects received from openai stream chunks
    to update the running tool_calls object.

    Args:
        tool_calls (List[ChoiceDeltaToolCall]): the list of tool calls
        tool_calls_delta (ChoiceDeltaToolCall): the delta to update tool_calls

    Returns:
        List[ChoiceDeltaToolCall]: the updated tool calls
    """
    ...

