"""
This type stub file was generated by pyright.
"""

import builtins
import typing

import pydantic
import pydantic.v1 as pydantic

if pydantic.__version__.startswith("1."): ...

class CloudDocument(pydantic.BaseModel):
    """
    Cloud document stored in S3.
    """

    text: str
    metadata: builtins.dict[str, typing.Any]
    excluded_embed_metadata_keys: list[str] | None
    excluded_llm_metadata_keys: list[str] | None
    page_positions: list[int] | None
    id: str
    def json(self, **kwargs: typing.Any) -> str: ...
    def dict(self, **kwargs: typing.Any) -> builtins.dict[str, typing.Any]: ...

    class Config:
        frozen = ...
        smart_union = ...
        json_encoders = ...
