"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Union

from llama_index.core.bridge.pydantic import BaseModel
from llama_index.core.schema import NodeWithScore
from llama_index.core.types import TokenAsyncGen, TokenGen

"""Response schema."""

@dataclass
class Response:
    """
    Response object.

    Returned if streaming=False.

    Attributes:
        response: The response text.

    """

    response: str | None
    source_nodes: list[NodeWithScore] = ...
    metadata: dict[str, Any] | None = ...
    def __str__(self) -> str:
        """Convert to string representation."""
        ...

    def get_formatted_sources(self, length: int = ...) -> str:
        """Get formatted sources text."""
        ...

@dataclass
class PydanticResponse:
    """
    PydanticResponse object.

    Returned if streaming=False.

    Attributes:
        response: The response text.

    """

    response: BaseModel | None
    source_nodes: list[NodeWithScore] = ...
    metadata: dict[str, Any] | None = ...
    def __str__(self) -> str:
        """Convert to string representation."""
        ...

    def __getattr__(self, name: str) -> Any:
        """Get attribute, but prioritize the pydantic  response object."""
        ...

    def __post_init_post_parse__(self) -> None:
        """
        This method is required.

        According to the Pydantic docs, if a stdlib dataclass (which this class
        is one) gets mixed with a BaseModel (in the sense that this gets used as a
        Field in another BaseModel), then this stdlib dataclass will automatically
        get converted to a pydantic.v1.dataclass.

        However, it appears that in that automatic conversion, this method
        is left as NoneType, which raises an error. To safeguard against that,
        we are explicitly defining this method as something that can be called.

        Sources:
            - https://docs.pydantic.dev/1.10/usage/dataclasses/#use-of-stdlib-dataclasses-with-basemodel
            - https://docs.pydantic.dev/1.10/usage/dataclasses/#initialize-hooks
        """
        ...

    def get_formatted_sources(self, length: int = ...) -> str:
        """Get formatted sources text."""
        ...

    def get_response(self) -> Response:
        """Get a standard response object."""
        ...

@dataclass
class StreamingResponse:
    """
    StreamingResponse object.

    Returned if streaming=True.

    Attributes:
        response_gen: The response generator.

    """

    response_gen: TokenGen
    source_nodes: list[NodeWithScore] = ...
    metadata: dict[str, Any] | None = ...
    response_txt: str | None = ...
    def __str__(self) -> str:
        """Convert to string representation."""
        ...

    def get_response(self) -> Response:
        """Get a standard response object."""
        ...

    def print_response_stream(self) -> None:
        """Print the response stream."""
        ...

    def get_formatted_sources(self, length: int = ..., trim_text: int = ...) -> str:
        """Get formatted sources text."""
        ...

@dataclass
class AsyncStreamingResponse:
    """
    AsyncStreamingResponse object.

    Returned if streaming=True while using async.

    Attributes:
        _async_response_gen: The response async generator.

    """

    response_gen: TokenAsyncGen
    source_nodes: list[NodeWithScore] = ...
    metadata: dict[str, Any] | None = ...
    response_txt: str | None = ...
    def __post_init__(self) -> None: ...
    def __str__(self) -> str:
        """Convert to string representation."""
        ...

    async def async_response_gen(self) -> TokenAsyncGen:
        """Yield the string response."""
        ...

    async def get_response(self) -> Response:
        """Get a standard response object."""
        ...

    async def print_response_stream(self) -> None:
        """Print the response stream."""
        ...

    def get_formatted_sources(self, length: int = ..., trim_text: int = ...) -> str:
        """Get formatted sources text."""
        ...

RESPONSE_TYPE = Union[Response, StreamingResponse, AsyncStreamingResponse, PydanticResponse]
