"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any

from llama_index.core.callbacks.schema import CBEventType

logger = ...
global_stack_trace = ...

class BaseCallbackHandler(ABC):
    """Base callback handler that can be used to track event starts and ends."""
    def __init__(
        self, event_starts_to_ignore: list[CBEventType], event_ends_to_ignore: list[CBEventType]
    ) -> None:
        """Initialize the base callback handler."""
        ...

    @abstractmethod
    def on_event_start(
        self,
        event_type: CBEventType,
        payload: dict[str, Any] | None = ...,
        event_id: str = ...,
        parent_id: str = ...,
        **kwargs: Any,
    ) -> str:
        """Run when an event starts and return id of event."""
        ...

    @abstractmethod
    def on_event_end(
        self,
        event_type: CBEventType,
        payload: dict[str, Any] | None = ...,
        event_id: str = ...,
        **kwargs: Any,
    ) -> None:
        """Run when an event ends."""
        ...

    @abstractmethod
    def start_trace(self, trace_id: str | None = ...) -> None:
        """Run when an overall trace is launched."""
        ...

    @abstractmethod
    def end_trace(
        self, trace_id: str | None = ..., trace_map: dict[str, list[str]] | None = ...
    ) -> None:
        """Run when an overall trace is exited."""
        ...
