"""
This type stub file was generated by pyright.
"""

import logging
from abc import ABC, abstractmethod
from contextvars import ContextVar
from typing import Any, Dict, List, Optional
from llama_index.core.callbacks.schema import BASE_TRACE_EVENT, CBEventType

logger = ...
global_stack_trace = ...
class BaseCallbackHandler(ABC):
    """Base callback handler that can be used to track event starts and ends."""
    def __init__(self, event_starts_to_ignore: List[CBEventType], event_ends_to_ignore: List[CBEventType]) -> None:
        """Initialize the base callback handler."""
        ...
    
    @abstractmethod
    def on_event_start(self, event_type: CBEventType, payload: Optional[Dict[str, Any]] = ..., event_id: str = ..., parent_id: str = ..., **kwargs: Any) -> str:
        """Run when an event starts and return id of event."""
        ...
    
    @abstractmethod
    def on_event_end(self, event_type: CBEventType, payload: Optional[Dict[str, Any]] = ..., event_id: str = ..., **kwargs: Any) -> None:
        """Run when an event ends."""
        ...
    
    @abstractmethod
    def start_trace(self, trace_id: Optional[str] = ...) -> None:
        """Run when an overall trace is launched."""
        ...
    
    @abstractmethod
    def end_trace(self, trace_id: Optional[str] = ..., trace_map: Optional[Dict[str, List[str]]] = ...) -> None:
        """Run when an overall trace is exited."""
        ...
    


