"""
This type stub file was generated by pyright.
"""

from typing import Any

from chromadb.api.types import Documents, EmbeddingFunction, Embeddings, Space

ENDPOINT = ...

class TogetherAIEmbeddingFunction(EmbeddingFunction[Documents]):
    """
    This class is used to get embeddings for a list of texts using the Together AI API.
    """
    def __init__(
        self, model_name: str, api_key: str | None = ..., api_key_env_var: str = ...
    ) -> None:
        """
        Initialize the TogetherAIEmbeddingFunction. See the docs for supported models here:
        https://docs.together.ai/docs/serverless-models#embedding-models

        Args:
            model_name: The name of the model to use for text embeddings.
            api_key: The API key to use for the Together AI API.
            api_key_env_var: The environment variable to use for the Together AI API key.
        """
        ...

    def __call__(self, input: Documents) -> Embeddings:
        """
        Embed a list of texts using the Together AI API.

        Args:
            input: A list of texts to embed.
        """
        ...

    @staticmethod
    def name() -> str: ...
    def default_space(self) -> Space: ...
    def supported_spaces(self) -> list[Space]: ...
    @staticmethod
    def build_from_config(config: dict[str, Any]) -> EmbeddingFunction[Documents]: ...
    def get_config(self) -> dict[str, Any]: ...
    def validate_config_update(
        self, old_config: dict[str, Any], new_config: dict[str, Any]
    ) -> None: ...
    @staticmethod
    def validate_config(config: dict[str, Any]) -> None:
        """
        Validate the configuration using the JSON schema.

        Args:
            config: Configuration to validate
        """
        ...
