"""
This type stub file was generated by pyright.
"""

import io
import os
import pathlib
import anyio
from typing import overload
from typing_extensions import TypeGuard
from ._types import Base64FileInput, FileContent, FileTypes, HttpxFileContent, HttpxFileTypes, HttpxRequestFiles, RequestFiles
from ._utils import is_mapping_t, is_sequence_t, is_tuple_t

def is_base64_file_input(obj: object) -> TypeGuard[Base64FileInput]:
    ...

def is_file_content(obj: object) -> TypeGuard[FileContent]:
    ...

def assert_is_file_content(obj: object, *, key: str | None = ...) -> None:
    ...

@overload
def to_httpx_files(files: None) -> None:
    ...

@overload
def to_httpx_files(files: RequestFiles) -> HttpxRequestFiles:
    ...

def to_httpx_files(files: RequestFiles | None) -> HttpxRequestFiles | None:
    ...

@overload
async def async_to_httpx_files(files: None) -> None:
    ...

@overload
async def async_to_httpx_files(files: RequestFiles) -> HttpxRequestFiles:
    ...

async def async_to_httpx_files(files: RequestFiles | None) -> HttpxRequestFiles | None:
    ...

