"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from typing import Any, Generic, TypeVar

from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.query_pipeline.query import (
    ChainableMixin,
    InputKeys,
    OutputKeys,
    QueryComponent,
)
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.indices.base import BaseIndex
from llama_index.core.objects.base_node_mapping import BaseObjectNodeMapping
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.schema import BaseNode, QueryType

"""Base object types."""
OT = TypeVar("OT")

class ObjectRetriever(ChainableMixin, Generic[OT]):
    """Object retriever."""
    def __init__(
        self,
        retriever: BaseRetriever,
        object_node_mapping: BaseObjectNodeMapping[OT],
        node_postprocessors: list[BaseNodePostprocessor] | None = ...,
    ) -> None: ...
    @property
    def retriever(self) -> BaseRetriever:
        """Retriever."""
        ...

    @property
    def object_node_mapping(self) -> BaseObjectNodeMapping[OT]:
        """Object node mapping."""
        ...

    @property
    def node_postprocessors(self) -> list[BaseNodePostprocessor]:
        """Node postprocessors."""
        ...

    def retrieve(self, str_or_query_bundle: QueryType) -> list[OT]: ...
    async def aretrieve(self, str_or_query_bundle: QueryType) -> list[OT]: ...

class ObjectRetrieverComponent(QueryComponent):
    """Object retriever component."""

    model_config = ...
    retriever: ObjectRetriever = ...
    def set_callback_manager(self, callback_manager: CallbackManager) -> None:
        """Set callback manager."""
        ...

    @property
    def input_keys(self) -> InputKeys:
        """Input keys."""
        ...

    @property
    def output_keys(self) -> OutputKeys:
        """Output keys."""
        ...

class ObjectIndex(Generic[OT]):
    """Object index."""
    def __init__(self, index: BaseIndex, object_node_mapping: BaseObjectNodeMapping) -> None: ...
    @property
    def index(self) -> BaseIndex:
        """Index."""
        ...

    @property
    def object_node_mapping(self) -> BaseObjectNodeMapping:
        """Object node mapping."""
        ...

    @classmethod
    def from_objects(
        cls,
        objects: Sequence[OT],
        object_mapping: BaseObjectNodeMapping | None = ...,
        from_node_fn: Callable[[BaseNode], OT] | None = ...,
        to_node_fn: Callable[[OT], BaseNode] | None = ...,
        index_cls: type[BaseIndex] = ...,
        **index_kwargs: Any,
    ) -> ObjectIndex: ...
    @classmethod
    def from_objects_and_index(
        cls,
        objects: Sequence[OT],
        index: BaseIndex,
        object_mapping: BaseObjectNodeMapping | None = ...,
        from_node_fn: Callable[[BaseNode], OT] | None = ...,
        to_node_fn: Callable[[OT], BaseNode] | None = ...,
    ) -> ObjectIndex: ...
    def insert_object(self, obj: Any) -> None: ...
    def as_retriever(
        self, node_postprocessors: list[BaseNodePostprocessor] | None = ..., **kwargs: Any
    ) -> ObjectRetriever: ...
    def as_node_retriever(self, **kwargs: Any) -> BaseRetriever: ...
    def persist(self, persist_dir: str = ..., obj_node_mapping_fname: str = ...) -> None: ...
    @classmethod
    def from_persist_dir(
        cls, persist_dir: str = ..., object_node_mapping: BaseObjectNodeMapping | None = ...
    ) -> ObjectIndex: ...
