"""
This type stub file was generated by pyright.
"""

from typing import Any

from llama_index.core.llms.llm import LLM
from llama_index.core.prompts.base import BasePromptTemplate
from llama_index.core.types import BaseOutputParser, BasePydanticProgram, Model

class LLMTextCompletionProgram(BasePydanticProgram[Model]):
    """
    LLM Text Completion Program.

    Uses generic LLM text completion + an output parser to generate a structured output.

    """
    def __init__(
        self,
        output_parser: BaseOutputParser,
        output_cls: type[Model],
        prompt: BasePromptTemplate,
        llm: LLM,
        verbose: bool = ...,
    ) -> None: ...
    @classmethod
    def from_defaults(
        cls,
        output_parser: BaseOutputParser | None = ...,
        output_cls: type[Model] | None = ...,
        prompt_template_str: str | None = ...,
        prompt: BasePromptTemplate | None = ...,
        llm: LLM | None = ...,
        verbose: bool = ...,
        **kwargs: Any,
    ) -> LLMTextCompletionProgram[Model]: ...
    @property
    def output_cls(self) -> type[Model]: ...
    @property
    def prompt(self) -> BasePromptTemplate: ...
    @prompt.setter
    def prompt(self, prompt: BasePromptTemplate) -> None: ...
    def __call__(
        self, llm_kwargs: dict[str, Any] | None = ..., *args: Any, **kwargs: Any
    ) -> Model: ...
    async def acall(
        self, llm_kwargs: dict[str, Any] | None = ..., *args: Any, **kwargs: Any
    ) -> Model: ...
