"""
This type stub file was generated by pyright.
"""

import torch
from compressed_tensors.quantization import QuantizationScheme
from torch import Tensor
from torch.nn.modules import Linear

class CompressedLinear(Linear):
    """
    Wrapper module for running a compressed forward pass of a quantized Linear module.
    The wrapped layer will decompressed on each forward call.

    """
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    @torch.no_grad()
    def from_linear(
        cls, module: Linear, quantization_scheme: QuantizationScheme, quantization_format: str
    ):  # -> Linear:
        """
        :param module: dense linear module to replace
        :param quantization_scheme: quantization config for the module to wrap
        :param quantization_format: compression format module is stored as
        :return: CompressedLinear module wrapping the input module
        """
        ...

    def forward(self, input: Tensor) -> Tensor:
        """
        Decompresses the weight, then runs the wrapped forward pass
        """
        ...
