"""
This type stub file was generated by pyright.
"""

import base64
import enum
import struct
import dns.enum
import dns.exception
import dns.immutable
import dns.ipv4
import dns.ipv6
import dns.name
import dns.rdata
import dns.rdtypes.util
import dns.renderer
import dns.tokenizer
import dns.wire

class UnknownParamKey(dns.exception.DNSException):
    """Unknown SVCB ParamKey"""
    ...


class ParamKey(dns.enum.IntEnum):
    """SVCB ParamKey"""
    MANDATORY = ...
    ALPN = ...
    NO_DEFAULT_ALPN = ...
    PORT = ...
    IPV4HINT = ...
    ECH = ...
    IPV6HINT = ...
    DOHPATH = ...
    OHTTP = ...


class Emptiness(enum.IntEnum):
    NEVER = ...
    ALWAYS = ...
    ALLOWED = ...


def key_to_text(key): # -> str:
    ...

_escaped = ...
@dns.immutable.immutable
class Param:
    """Abstract base class for SVCB parameters"""
    @classmethod
    def emptiness(cls): # -> Literal[Emptiness.NEVER]:
        ...
    


@dns.immutable.immutable
class GenericParam(Param):
    """Generic SVCB parameter"""
    def __init__(self, value) -> None:
        ...
    
    @classmethod
    def emptiness(cls): # -> Literal[Emptiness.ALLOWED]:
        ...
    
    @classmethod
    def from_value(cls, value): # -> Self | None:
        ...
    
    def to_text(self): # -> str:
        ...
    
    @classmethod
    def from_wire_parser(cls, parser, origin=...): # -> Self | None:
        ...
    
    def to_wire(self, file, origin=...): # -> None:
        ...
    


@dns.immutable.immutable
class MandatoryParam(Param):
    def __init__(self, keys) -> None:
        ...
    
    @classmethod
    def from_value(cls, value): # -> Self:
        ...
    
    def to_text(self): # -> str:
        ...
    
    @classmethod
    def from_wire_parser(cls, parser, origin=...): # -> Self:
        ...
    
    def to_wire(self, file, origin=...): # -> None:
        ...
    


@dns.immutable.immutable
class ALPNParam(Param):
    def __init__(self, ids) -> None:
        ...
    
    @classmethod
    def from_value(cls, value): # -> Self:
        ...
    
    def to_text(self): # -> str:
        ...
    
    @classmethod
    def from_wire_parser(cls, parser, origin=...): # -> Self:
        ...
    
    def to_wire(self, file, origin=...): # -> None:
        ...
    


@dns.immutable.immutable
class NoDefaultALPNParam(Param):
    @classmethod
    def emptiness(cls): # -> Literal[Emptiness.ALWAYS]:
        ...
    
    @classmethod
    def from_value(cls, value): # -> None:
        ...
    
    def to_text(self):
        ...
    
    @classmethod
    def from_wire_parser(cls, parser, origin=...): # -> None:
        ...
    
    def to_wire(self, file, origin=...):
        ...
    


@dns.immutable.immutable
class PortParam(Param):
    def __init__(self, port) -> None:
        ...
    
    @classmethod
    def from_value(cls, value): # -> Self:
        ...
    
    def to_text(self): # -> str:
        ...
    
    @classmethod
    def from_wire_parser(cls, parser, origin=...): # -> Self:
        ...
    
    def to_wire(self, file, origin=...): # -> None:
        ...
    


@dns.immutable.immutable
class IPv4HintParam(Param):
    def __init__(self, addresses) -> None:
        ...
    
    @classmethod
    def from_value(cls, value): # -> Self:
        ...
    
    def to_text(self): # -> LiteralString:
        ...
    
    @classmethod
    def from_wire_parser(cls, parser, origin=...): # -> Self:
        ...
    
    def to_wire(self, file, origin=...): # -> None:
        ...
    


@dns.immutable.immutable
class IPv6HintParam(Param):
    def __init__(self, addresses) -> None:
        ...
    
    @classmethod
    def from_value(cls, value): # -> Self:
        ...
    
    def to_text(self): # -> LiteralString:
        ...
    
    @classmethod
    def from_wire_parser(cls, parser, origin=...): # -> Self:
        ...
    
    def to_wire(self, file, origin=...): # -> None:
        ...
    


@dns.immutable.immutable
class ECHParam(Param):
    def __init__(self, ech) -> None:
        ...
    
    @classmethod
    def from_value(cls, value): # -> Self:
        ...
    
    def to_text(self): # -> str:
        ...
    
    @classmethod
    def from_wire_parser(cls, parser, origin=...): # -> Self:
        ...
    
    def to_wire(self, file, origin=...): # -> None:
        ...
    


@dns.immutable.immutable
class OHTTPParam(Param):
    @classmethod
    def emptiness(cls): # -> Literal[Emptiness.ALWAYS]:
        ...
    
    @classmethod
    def from_value(cls, value): # -> None:
        ...
    
    def to_text(self):
        ...
    
    @classmethod
    def from_wire_parser(cls, parser, origin=...): # -> None:
        ...
    
    def to_wire(self, file, origin=...):
        ...
    


_class_for_key = ...
@dns.immutable.immutable
class SVCBBase(dns.rdata.Rdata):
    """Base class for SVCB-like records"""
    __slots__ = ...
    def __init__(self, rdclass, rdtype, priority, target, params) -> None:
        ...
    
    def to_text(self, origin=..., relativize=..., **kw): # -> str:
        ...
    
    @classmethod
    def from_text(cls, rdclass, rdtype, tok, origin=..., relativize=..., relativize_to=...): # -> Self:
        ...
    
    @classmethod
    def from_wire_parser(cls, rdclass, rdtype, parser, origin=...): # -> Self:
        ...
    


