"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

__all__ = ["is_available", "flags", "set_flags"]

def is_available():  # -> bool:
    r"""Return whether PyTorch is built with NNPACK support."""
    ...

def set_flags(_enabled):  # -> tuple[bool]:
    r"""Set if nnpack is enabled globally"""
    ...

@contextmanager
def flags(enabled=...):  # -> Generator[None, Any, None]:
    r"""Context manager for setting if nnpack is enabled globally"""
    ...
