"""
This type stub file was generated by pyright.
"""

from datetime import datetime

from .base import BaseSpan

class SimpleSpan(BaseSpan):
    """Simple span class."""

    start_time: datetime = ...
    end_time: datetime | None = ...
    duration: float = ...
    metadata: dict | None = ...
