"""
This type stub file was generated by pyright.
"""

import copy
import warnings
import torch
from dataclasses import asdict
from typing import Any, Optional, Union
from torch._subclasses import FakeTensor
from torch.ao.quantization import FixedQParamsFakeQuantize, FixedQParamsObserver, ObserverBase, ObserverOrFakeQuantize, PlaceholderObserver, _DerivedObserverOrFakeQuantize
from torch.ao.quantization.backend_config import BackendConfig, DTypeConfig, get_native_backend_config
from torch.ao.quantization.backend_config.utils import get_fusion_pattern_to_root_node_getter, get_module_to_qat_module, get_pattern_to_dtype_configs
from torch.ao.quantization.observer import _PartialWrapper, _is_activation_post_process
from torch.ao.quantization.qconfig import QConfigAny, _is_reuse_input_qconfig
from torch.ao.quantization.qconfig_mapping import QConfigMapping
from torch.ao.quantization.quantize import convert, propagate_qconfig_
from torch.ao.quantization.quantizer import DerivedQuantizationSpec, EdgeOrNode, FixedQParamsQuantizationSpec, QuantizationSpec, QuantizationSpecBase, SharedQuantizationSpec
from torch.ao.quantization.utils import NodePattern, Pattern, _parent_name, get_qconfig_dtypes, get_swapped_custom_module_class
from torch.fx import GraphModule
from torch.fx.graph import Graph, Node
from torch.fx.node import Argument
from ._equalize import is_equalization_observer, node_supports_equalization
from .custom_config import PrepareCustomConfig, StandaloneModuleConfigEntry
from .match_utils import _MatchResultWithQConfig, _find_matches
from .pattern_utils import _sorted_patterns_dict
from .qconfig_mapping_utils import _generate_node_name_to_qconfig, _get_flattened_qconfig_dict, _update_qconfig_for_fusion, _update_qconfig_for_qat
from .quantize_handler import QuantizeHandler, _default_root_node_getter, _get_pattern_to_quantize_handlers
from .utils import NON_QUANTIZABLE_WEIGHT_OPS, ObservedGraphModuleAttrs, _insert_dequant_stubs_for_custom_module_lstm_output, _is_custom_module_lstm, _maybe_get_custom_module_lstm_from_node_arg, _qconfig_satisfies_dtype_config_constraints, all_node_args_have_no_tensors, assert_and_get_unique_device, get_custom_module_class_keys, get_new_attr_name_with_prefix, get_non_observable_arg_indexes_and_types, node_arg_is_bias, node_arg_is_weight

__all__ = ["insert_observers_for_model", "prepare", "propagate_dtypes_for_known_nodes"]
_DO_NOT_OBS_DTYPE_LIST = ...
_OBS_DTYPE_LIST = ...
_DEFAULT_FP32_OBS_OR_FQ_CTR = ...
_DEFAULT_FP32_QCONFIG_FOR_TARGET_DTYPE_INFO = ...
_DEFAULT_QUINT8_QCONFIG_FOR_TARGET_DTYPE_INFO = ...
def propagate_dtypes_for_known_nodes(graph: Graph, node_name_to_match_result_with_qconfig: dict[str, _MatchResultWithQConfig]) -> None:
    """
    Currently we assume that inputs to the graph are either `torch.float` or
    `torch.quint8`, which is not always correct. For ops such as
    `x.masked_fill(mask, value)`, we know that the dtype of  `mask` is a
    `BoolTensor`. Propagate this information throughout the graph.

    Note: not all dtypes in the graph will be correct after this pass, but a
    higher percentage of them will be correct. Hopefully in the future we can
    replace this with a better way to reason about dtypes of tensors.
    """
    ...

def insert_observers_for_model(model: GraphModule, node_name_to_match_result_with_qconfig: dict[str, _MatchResultWithQConfig], node_name_to_qconfig: dict[str, QConfigAny], prepare_custom_config: PrepareCustomConfig, equalization_config_map: dict[str, Any], backend_config: BackendConfig, observed_node_names: set[str], is_qat: bool) -> Optional[Node]:
    """
    Inserts observers, using the following high level algorithm:

    For each node in the graph:
      1. determine the target dtype of this node in the quantized graph, and save
           it for future steps
      2. determine the target dtype or all args and kwargs of this node
      3. if any arg or kwarg's target dtype does not match the current node's
           dtype, insert an observer
      4. if the current node needs an output observer, insert it

    For example:

    - starting graph:
        x0 -> linear -> x1

    - observed graph after processing x0:
        x0(fp32)

    - observed graph after processing linear:
        x0(fp32) -> x0_obs0(int8) -> linear(int8) -> linear_obs0(int8)

    - observed graph after processing x1:
        x0(fp32) -> x0_obs0(int8) -> linear(int8) -> linear_obs0(int8) -> x1

    After a node is processed, the naive observer placement is guaranteed to be
    complete for that node and all of its predecessors. There can be future
    passes which optimize the graph by deduplicating observers, etc.
    """
    ...

def prepare(model: GraphModule, qconfig_mapping: Union[QConfigMapping, dict[str, Any]], is_qat: bool, node_name_to_scope: dict[str, tuple[str, type]], example_inputs: tuple[Any, ...], prepare_custom_config: Union[PrepareCustomConfig, dict[str, Any], None] = ..., _equalization_config: Union[QConfigMapping, dict[str, Any], None] = ..., backend_config: Union[BackendConfig, dict[str, Any], None] = ..., is_standalone_module: bool = ...) -> GraphModule:
    """standalone_module means it a submodule that is not inlined in
    parent module, and will be quantized separately as one unit.

    How the standalone module is observed is specified by `input_quantized_idxs` and
    `output_quantized_idxs` in the prepare_custom_config for the standalone module
    Args:
        node_name_to_scope: mapping from node name to the scope of the module which contains the node.
        The scope is a tuple of fully qualified path of the module and the type of the module
    Returns:
        model(GraphModule): prepared standalone module
        attributes related to standalone module
        in model.meta["_observed_graph_module_attrs"]:
            is_observed_standalone_module (bool): boolean value that shows whether the
            current model is a observed standalone module or not
            standalone_module_input_quantized_idxs(List[Int]): a list of
                indexes for the graph input that is expected to be quantized,
                same as input_quantized_idxs configuration provided
                for the standalone module
            standalone_module_output_quantized_idxs(List[Int]): a list of
                indexs for the graph output that is quantized
                same as input_quantized_idxs configuration provided
                for the standalone module
    """
    ...

