"""
This type stub file was generated by pyright.
"""

import fsspec
from abc import ABC, abstractmethod
from collections.abc import Callable, MutableMapping
from typing import Dict, Generic, List, Optional, Tuple, TypeVar

DEFAULT_COLLECTION = ...
DEFAULT_BATCH_SIZE = ...
class BaseKVStore(ABC):
    """Base key-value store."""
    @abstractmethod
    def put(self, key: str, val: dict, collection: str = ...) -> None:
        ...
    
    @abstractmethod
    async def aput(self, key: str, val: dict, collection: str = ...) -> None:
        ...
    
    def put_all(self, kv_pairs: List[Tuple[str, dict]], collection: str = ..., batch_size: int = ...) -> None:
        ...
    
    async def aput_all(self, kv_pairs: List[Tuple[str, dict]], collection: str = ..., batch_size: int = ...) -> None:
        ...
    
    @abstractmethod
    def get(self, key: str, collection: str = ...) -> Optional[dict]:
        ...
    
    @abstractmethod
    async def aget(self, key: str, collection: str = ...) -> Optional[dict]:
        ...
    
    @abstractmethod
    def get_all(self, collection: str = ...) -> Dict[str, dict]:
        ...
    
    @abstractmethod
    async def aget_all(self, collection: str = ...) -> Dict[str, dict]:
        ...
    
    @abstractmethod
    def delete(self, key: str, collection: str = ...) -> bool:
        ...
    
    @abstractmethod
    async def adelete(self, key: str, collection: str = ...) -> bool:
        ...
    


class BaseInMemoryKVStore(BaseKVStore):
    """Base in-memory key-value store."""
    @abstractmethod
    def persist(self, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        ...
    
    @classmethod
    @abstractmethod
    def from_persist_path(cls, persist_path: str) -> BaseInMemoryKVStore:
        """Create a BaseInMemoryKVStore from a persist directory."""
        ...
    


MutableMappingT = TypeVar("MutableMappingT", bound=MutableMapping[str, dict])
class MutableMappingKVStore(Generic[MutableMappingT], BaseKVStore):
    """
    MutableMapping Key-Value store.

    Args:
        mapping_factory (Callable[[], MutableMapping[str, dict]): the mutable mapping factory

    """
    def __init__(self, mapping_factory: Callable[[], MutableMappingT]) -> None:
        """Initialize a MutableMappingKVStore."""
        ...
    
    def __getstate__(self) -> dict:
        ...
    
    def __setstate__(self, state: dict) -> None:
        ...
    
    def put(self, key: str, val: dict, collection: str = ...) -> None:
        """Put a key-value pair into the store."""
        ...
    
    async def aput(self, key: str, val: dict, collection: str = ...) -> None:
        """Put a key-value pair into the store."""
        ...
    
    def get(self, key: str, collection: str = ...) -> Optional[dict]:
        """Get a value from the store."""
        ...
    
    async def aget(self, key: str, collection: str = ...) -> Optional[dict]:
        """Get a value from the store."""
        ...
    
    def get_all(self, collection: str = ...) -> Dict[str, dict]:
        """Get all values from the store."""
        ...
    
    async def aget_all(self, collection: str = ...) -> Dict[str, dict]:
        """Get all values from the store."""
        ...
    
    def delete(self, key: str, collection: str = ...) -> bool:
        """Delete a value from the store."""
        ...
    
    async def adelete(self, key: str, collection: str = ...) -> bool:
        """Delete a value from the store."""
        ...
    
    def persist(self, persist_path: str, fs: Optional[fsspec.AbstractFileSystem] = ...) -> None:
        """Persist the store."""
        ...
    
    def from_persist_path(cls, persist_path: str) -> MutableMappingKVStore:
        """Create a MutableMappingKVStore from a persist directory."""
        ...
    


