"""
This type stub file was generated by pyright.
"""

from ..._compat import cached_property
from ..._resource import AsyncAPIResource, SyncAPIResource
from .alpha.alpha import (
    Alpha,
    AlphaWithRawResponse,
    AlphaWithStreamingResponse,
    AsyncAlpha,
    AsyncAlphaWithRawResponse,
    AsyncAlphaWithStreamingResponse,
)
from .checkpoints.checkpoints import (
    AsyncCheckpoints,
    AsyncCheckpointsWithRawResponse,
    AsyncCheckpointsWithStreamingResponse,
    Checkpoints,
    CheckpointsWithRawResponse,
    CheckpointsWithStreamingResponse,
)
from .jobs.jobs import (
    AsyncJobs,
    AsyncJobsWithRawResponse,
    AsyncJobsWithStreamingResponse,
    Jobs,
    JobsWithRawResponse,
    JobsWithStreamingResponse,
)

__all__ = ["FineTuning", "AsyncFineTuning"]

class FineTuning(SyncAPIResource):
    @cached_property
    def jobs(self) -> Jobs: ...
    @cached_property
    def checkpoints(self) -> Checkpoints: ...
    @cached_property
    def alpha(self) -> Alpha: ...
    @cached_property
    def with_raw_response(self) -> FineTuningWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.

        For more information, see https://www.github.com/openai/openai-python#accessing-raw-response-data-eg-headers
        """
        ...

    @cached_property
    def with_streaming_response(self) -> FineTuningWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.

        For more information, see https://www.github.com/openai/openai-python#with_streaming_response
        """
        ...

class AsyncFineTuning(AsyncAPIResource):
    @cached_property
    def jobs(self) -> AsyncJobs: ...
    @cached_property
    def checkpoints(self) -> AsyncCheckpoints: ...
    @cached_property
    def alpha(self) -> AsyncAlpha: ...
    @cached_property
    def with_raw_response(self) -> AsyncFineTuningWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.

        For more information, see https://www.github.com/openai/openai-python#accessing-raw-response-data-eg-headers
        """
        ...

    @cached_property
    def with_streaming_response(self) -> AsyncFineTuningWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.

        For more information, see https://www.github.com/openai/openai-python#with_streaming_response
        """
        ...

class FineTuningWithRawResponse:
    def __init__(self, fine_tuning: FineTuning) -> None: ...
    @cached_property
    def jobs(self) -> JobsWithRawResponse: ...
    @cached_property
    def checkpoints(self) -> CheckpointsWithRawResponse: ...
    @cached_property
    def alpha(self) -> AlphaWithRawResponse: ...

class AsyncFineTuningWithRawResponse:
    def __init__(self, fine_tuning: AsyncFineTuning) -> None: ...
    @cached_property
    def jobs(self) -> AsyncJobsWithRawResponse: ...
    @cached_property
    def checkpoints(self) -> AsyncCheckpointsWithRawResponse: ...
    @cached_property
    def alpha(self) -> AsyncAlphaWithRawResponse: ...

class FineTuningWithStreamingResponse:
    def __init__(self, fine_tuning: FineTuning) -> None: ...
    @cached_property
    def jobs(self) -> JobsWithStreamingResponse: ...
    @cached_property
    def checkpoints(self) -> CheckpointsWithStreamingResponse: ...
    @cached_property
    def alpha(self) -> AlphaWithStreamingResponse: ...

class AsyncFineTuningWithStreamingResponse:
    def __init__(self, fine_tuning: AsyncFineTuning) -> None: ...
    @cached_property
    def jobs(self) -> AsyncJobsWithStreamingResponse: ...
    @cached_property
    def checkpoints(self) -> AsyncCheckpointsWithStreamingResponse: ...
    @cached_property
    def alpha(self) -> AsyncAlphaWithStreamingResponse: ...
