"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, TypeVar
from dataclasses import dataclass
from pydantic import SecretStr
from chromadb.config import Component, System

T = TypeVar("T")
S = TypeVar("S")
class AuthError(Exception):
    ...


ClientAuthHeaders = Dict[str, SecretStr]
class ClientAuthProvider(Component):
    """
    ClientAuthProvider is responsible for providing authentication headers for
    client requests. Client implementations (in our case, just the FastAPI
    client) must inject these headers into their requests.
    """
    def __init__(self, system: System) -> None:
        ...
    
    @abstractmethod
    def authenticate(self) -> ClientAuthHeaders:
        ...
    


@dataclass
class UserIdentity:
    """
    UserIdentity represents the identity of a user. In general, not all fields
    will be populated, and the fields that are populated will depend on the
    authentication provider.

    The idea is that the AuthenticationProvider is responsible for populating
    _all_ information known about the user, and the AuthorizationProvider is
    responsible for making decisions based on that information.
    """
    user_id: str
    tenant: Optional[str] = ...
    databases: Optional[List[str]] = ...
    attributes: Optional[Dict[str, Any]] = ...


class ServerAuthenticationProvider(Component):
    """
    ServerAuthenticationProvider is responsible for authenticating requests. If
    a ServerAuthenticationProvider is configured, it will be called by the
    server to authenticate requests. If no ServerAuthenticationProvider is
    configured, all requests will be authenticated.

    The ServerAuthenticationProvider should return a UserIdentity object if the
    request is authenticated for use by the ServerAuthorizationProvider.
    """
    def __init__(self, system: System) -> None:
        ...
    
    @abstractmethod
    def authenticate_or_raise(self, headers: Dict[str, str]) -> UserIdentity:
        ...
    
    def ignore_operation(self, verb: str, path: str) -> bool:
        ...
    
    def read_creds_or_creds_file(self) -> List[str]:
        ...
    
    def singleton_tenant_database_if_applicable(self, user: Optional[UserIdentity]) -> Tuple[Optional[str], Optional[str]]:
        """
        If settings.chroma_overwrite_singleton_tenant_database_access_from_auth
        is False, this function always returns (None, None).

        If settings.chroma_overwrite_singleton_tenant_database_access_from_auth
        is True, follows the following logic:
        - If the user only has access to a single tenant, this function will
          return that tenant as its first return value.
        - If the user only has access to a single database, this function will
          return that database as its second return value. If the user has
          access to multiple tenants and/or databases, including "*", this
          function will return None for the corresponding value(s).
        - If the user has access to multiple tenants and/or databases this
          function will return None for the corresponding value(s).
        """
        ...
    


class AuthzAction(str, Enum):
    """
    The set of actions that can be authorized by the authorization provider.
    """
    RESET = ...
    CREATE_TENANT = ...
    GET_TENANT = ...
    CREATE_DATABASE = ...
    GET_DATABASE = ...
    DELETE_DATABASE = ...
    LIST_DATABASES = ...
    LIST_COLLECTIONS = ...
    COUNT_COLLECTIONS = ...
    CREATE_COLLECTION = ...
    GET_OR_CREATE_COLLECTION = ...
    GET_COLLECTION = ...
    DELETE_COLLECTION = ...
    UPDATE_COLLECTION = ...
    ADD = ...
    DELETE = ...
    GET = ...
    QUERY = ...
    COUNT = ...
    UPDATE = ...
    UPSERT = ...


@dataclass
class AuthzResource:
    """
    The resource being accessed in an authorization request.
    """
    tenant: Optional[str]
    database: Optional[str]
    collection: Optional[str]
    ...


class ServerAuthorizationProvider(Component):
    """
    ServerAuthorizationProvider is responsible for authorizing requests. If a
    ServerAuthorizationProvider is configured, it will be called by the server
    to authorize requests. If no ServerAuthorizationProvider is configured, all
    requests will be authorized.

    ServerAuthorizationProvider should raise an exception if the request is not
    authorized.
    """
    def __init__(self, system: System) -> None:
        ...
    
    @abstractmethod
    def authorize_or_raise(self, user: UserIdentity, action: AuthzAction, resource: AuthzResource) -> None:
        ...
    
    def read_config_or_config_file(self) -> List[str]:
        ...
    


