"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Sequence, Type
from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.node_parser.node_utils import build_nodes_from_splits
from llama_index.core.node_parser.file.html import HTMLNodeParser
from llama_index.core.node_parser.file.json import JSONNodeParser
from llama_index.core.node_parser.file.markdown import MarkdownNodeParser
from llama_index.core.node_parser.interface import NodeParser
from llama_index.core.schema import BaseNode, MetadataMode
from llama_index.core.utils import get_tqdm_iterable

"""Simple file node parser."""
FILE_NODE_PARSERS: Dict[str, Type[NodeParser]] = ...
class SimpleFileNodeParser(NodeParser):
    """
    Simple file node parser.

    Splits a document loaded from a file into Nodes using logic based on the file type
    automatically detects the NodeParser to use based on file type

    Args:
        include_metadata (bool): whether to include metadata in nodes
        include_prev_next_rel (bool): whether to include prev/next relationships

    """
    @classmethod
    def from_defaults(cls, include_metadata: bool = ..., include_prev_next_rel: bool = ..., callback_manager: Optional[CallbackManager] = ...) -> SimpleFileNodeParser:
        ...
    
    @classmethod
    def class_name(cls) -> str:
        """Get class name."""
        ...
    


