"""
This type stub file was generated by pyright.
"""

from llama_index.core.callbacks.base import CallbackManager
from llama_index.core.node_parser.interface import NodeParser

"""Simple file node parser."""
FILE_NODE_PARSERS: dict[str, type[NodeParser]] = ...

class SimpleFileNodeParser(NodeParser):
    """
    Simple file node parser.

    Splits a document loaded from a file into Nodes using logic based on the file type
    automatically detects the NodeParser to use based on file type

    Args:
        include_metadata (bool): whether to include metadata in nodes
        include_prev_next_rel (bool): whether to include prev/next relationships

    """
    @classmethod
    def from_defaults(
        cls,
        include_metadata: bool = ...,
        include_prev_next_rel: bool = ...,
        callback_manager: CallbackManager | None = ...,
    ) -> SimpleFileNodeParser: ...
    @classmethod
    def class_name(cls) -> str:
        """Get class name."""
        ...
