"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Dict, Optional, Sequence, Union
from llama_index.core.base.base_retriever import BaseRetriever
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.data_structs.data_structs import IndexList
from llama_index.core.indices.base import BaseIndex
from llama_index.core.llms.llm import LLM
from llama_index.core.schema import BaseNode, IndexNode
from llama_index.core.settings import Settings
from llama_index.core.storage.docstore.types import RefDocInfo
from llama_index.core.utils import get_tqdm_iterable

"""
Summary index.

A simple data structure where LlamaIndex iterates through document chunks
in sequence in order to answer a given query.

"""
class ListRetrieverMode(str, Enum):
    DEFAULT = ...
    EMBEDDING = ...
    LLM = ...


class SummaryIndex(BaseIndex[IndexList]):
    """
    Summary Index.

    The summary index is a simple data structure where nodes are stored in
    a sequence. During index construction, the document texts are
    chunked up, converted to nodes, and stored in a list.

    During query time, the summary index iterates through the nodes
    with some optional filter parameters, and synthesizes an
    answer from all the nodes.

    Args:
        text_qa_template (Optional[BasePromptTemplate]): A Question-Answer Prompt
            (see :ref:`Prompt-Templates`).
            NOTE: this is a deprecated field.
        show_progress (bool): Whether to show tqdm progress bars. Defaults to False.

    """
    index_struct_cls = ...
    def __init__(self, nodes: Optional[Sequence[BaseNode]] = ..., objects: Optional[Sequence[IndexNode]] = ..., index_struct: Optional[IndexList] = ..., show_progress: bool = ..., **kwargs: Any) -> None:
        """Initialize params."""
        ...
    
    def as_retriever(self, retriever_mode: Union[str, ListRetrieverMode] = ..., llm: Optional[LLM] = ..., embed_model: Optional[BaseEmbedding] = ..., **kwargs: Any) -> BaseRetriever:
        ...
    
    @property
    def ref_doc_info(self) -> Dict[str, RefDocInfo]:
        """Retrieve a dict mapping of ingested documents and their nodes+metadata."""
        ...
    


GPTListIndex = SummaryIndex
ListIndex = SummaryIndex
