"""
This type stub file was generated by pyright.
"""

from typing import Any

import triton
import triton.language as tl
from triton import Config
from triton.backends.compiler import GPUTarget
from triton.compiler import CompiledKernel
from triton.compiler.compiler import ASTSource
from triton.language.extra import libdevice
from triton.language.standard import _log2
from triton.runtime.autotuner import OutOfResources, PTXASError
from triton.runtime.jit import KernelInterface

if triton is not None:
    libdevice = ...
    math = ...
else:
    class OutOfResources(Exception): ...
    class PTXASError(Exception): ...

    Config = ...
    CompiledKernel = ...
    KernelInterface = ...
    ASTSource = ...
    GPUTarget = ...
    _log2 = ...
    libdevice = ...
    math = ...
    class triton:
        @staticmethod
        def jit(*args: Any, **kwargs: Any) -> Any: ...

    class tl:
        @staticmethod
        def constexpr(val: Any) -> Any: ...

        tensor = Any
        dtype = Any

def cc_warp_size(cc: str | int) -> int: ...

autograd_profiler = ...
__all__ = [
    "Config",
    "CompiledKernel",
    "OutOfResources",
    "KernelInterface",
    "PTXASError",
    "ASTSource",
    "GPUTarget",
    "tl",
    "_log2",
    "libdevice",
    "math",
    "triton",
    "cc_warp_size",
]
